/**
 * Procedural Animation Types
 *
 * Parametric animation presets that add life to sprite characters
 * through subtle body movements during dialogue.
 */

export type ProceduralPreset =
  | 'idle'
  | 'talking'
  | 'excited'
  | 'nervous'
  | 'sad'
  | 'dramatic'
  | 'none'

/** Per-part delta transforms generated by procedural animation */
export interface ProceduralTransform {
  dx: number
  dy: number
  dRotation: number
  dScaleX: number
  dScaleY: number
}

/** Configuration for a procedural animation preset */
export interface ProceduralPresetConfig {
  id: ProceduralPreset
  label: string
  description: string
  /** Oscillation parameters per body part */
  body: OscillationParams
  head: OscillationParams
  hair: OscillationParams
  viseme: OscillationParams
}

/** Parameters controlling a sine/cosine oscillation */
export interface OscillationParams {
  /** X displacement amplitude in pixels */
  xAmplitude: number
  /** Y displacement amplitude in pixels */
  yAmplitude: number
  /** X oscillation frequency in Hz */
  xFrequency: number
  /** Y oscillation frequency in Hz */
  yFrequency: number
  /** Rotation amplitude in degrees */
  rotationAmplitude: number
  /** Rotation frequency in Hz */
  rotationFrequency: number
  /** Scale oscillation amplitude (0 = no scaling) */
  scaleAmplitude: number
  /** Scale oscillation frequency in Hz */
  scaleFrequency: number
  /** Phase offset in radians (for part synchronization) */
  phaseOffset: number
}
