export { registerMotionGraphic, getMotionGraphic, getAllMotionGraphics, getMotionGraphicsByCategory } from './registry'
export { resolveTemplateType } from './resolver'

// ── Core kinetic typography templates ──────────────────────────────────
import './templates/KineticImpactBurst'
import './templates/KineticNeonWave'
import './templates/KineticGlitchSlam'
import './templates/KineticTypewriter'
import './templates/KineticBounce'
import './templates/KineticCinematicReveal'
import './templates/KineticStreetPoster'
import './templates/KineticGravityDrop'
import './templates/KineticMatrixRain'
import './templates/KineticLiquidFill'
import './templates/KineticNeonStreet'
import './templates/KineticVintagePunk'
import './templates/KineticJapaneseStreet'
import './templates/KineticConcertFlyer'
import './templates/KineticPropaganda'
import './templates/KineticGoldLuxury'
import './templates/KineticRetroPixel'
import './templates/KineticFogDrift'
import './templates/KineticElectricPulse'
import './templates/KineticBloodDrip'
import './templates/KineticWatercolorBleed'
import './templates/KineticSciFiHud'
import './templates/KineticGraffitiTag'
import './templates/KineticWoodblockStamp'
import './templates/KineticNewspaperHeadline'
import './templates/KineticTornLayers'
import './templates/KineticStencilSpray'
import './templates/KineticBlackletter'
import './templates/KineticRaveFluo'
import './templates/KineticMinimalPaste'
import './templates/KineticFireEmber'
import './templates/KineticIceShatter'
import './templates/KineticComicBoom'
import './templates/KineticChalkBoard'
import './templates/KineticVaporwave'
import './templates/KineticHologramFlicker'
import './templates/KineticSandErosion'
import './templates/KineticNeonOutline'
import './templates/KineticCyberGlitch'
import './templates/KineticAuroraWave'
import './templates/KineticElectricArc'
import './templates/KineticFlipBoard'
import './templates/KineticPaperCut'
import './templates/KineticSmokeReveal'
import './templates/KineticSpiralVortex'
import './templates/KineticParticleText'
import './templates/KineticFacelessType'

// ── Retro & aesthetic ──────────────────────────────────────────────────
import './templates/KineticVHSTracking'
import './templates/KineticCRTMonitor'
import './templates/KineticRetroWave'
import './templates/KineticY2KBubble'
import './templates/KineticBrutalType'
import './templates/KineticGlitchcore'
import './templates/KineticRetroGame8Bit'
import './templates/KineticDarkAcademia'
import './templates/KineticCottagecore'
import './templates/KineticCyberpunkNeon'
import './templates/KineticVinylRecord'
import './templates/KineticStaticNoise'

// ── Cultural / world art traditions ────────────────────────────────────
import './templates/KineticAnimeImpact'
import './templates/KineticMangaSoundEffect'
import './templates/KineticMangaScreentone'
import './templates/KineticWebtoonCaption'
import './templates/KineticBollywoodTitle'
import './templates/KineticArabicCalligraphy'
import './templates/KineticChineseBrush'
import './templates/KineticAfricanTextile'
import './templates/KineticDiaDeLosMuertos'
import './templates/KineticCelticKnot'
import './templates/KineticRussianConstructivist'
import './templates/KineticArtNouveau'
import './templates/KineticArtDeco'
import './templates/KineticUkiyoe'
import './templates/KineticAboriginalDot'
import './templates/KineticRangoli'
import './templates/KineticMehndi'
import './templates/KineticPersianMiniature'
import './templates/KineticGrecoRoman'
import './templates/KineticNativeAmericanPattern'

// ── Nature / organic ───────────────────────────────────────────────────
import './templates/KineticVineGrow'
import './templates/KineticWaterDissolve'
import './templates/KineticInkBleed'
import './templates/KineticPaintSplatter'
import './templates/KineticTextMelt'
import './templates/KineticStonecrumble'
import './templates/KineticLeafParticles'
import './templates/KineticSnowfall'
import './templates/KineticPetalBurst'
import './templates/KineticDustCloud'
import './templates/KineticButterflyText'
import './templates/KineticFrostForm'
import './templates/KineticPencilSketch'
import './templates/KineticClayMorph'
import './templates/KineticPaperFold'
import './templates/KineticBookPageFlip'
import './templates/KineticErosionWeather'
import './templates/KineticMagmaFlow'
import './templates/KineticOceanWave'
import './templates/KineticMossGrowth'
import './templates/KineticRainDrop'
import './templates/KineticAutumnLeaves'
import './templates/KineticCherryBlossom'
import './templates/KineticDesertDunes'
import './templates/KineticForestMist'
import './templates/KineticNorthernLights'
import './templates/KineticNorthernSky'
import './templates/KineticOceanWaves'
import './templates/KineticRainyWindow'
import './templates/KineticStarryNight'
import './templates/KineticSunrise'
import './templates/KineticSunsetGlow'
import './templates/KineticThunderstorm'

// ── Geometric & abstract ───────────────────────────────────────────────
import './templates/KineticCircleFrame'
import './templates/KineticTriangleShard'
import './templates/KineticHexGrid'
import './templates/KineticConcentricRings'
import './templates/KineticLineGrid'
import './templates/KineticDiamondReveal'
import './templates/KineticZigzagBorder'
import './templates/KineticDotMatrix'
import './templates/KineticWavyLines'
import './templates/KineticMosaicReveal'
import './templates/KineticCircleRevealTransition'
import './templates/KineticSpiralIn'
import './templates/KineticWireframe'
import './templates/KineticVenetianBlind'
import './templates/KineticAccordionFold'
import './templates/KineticZipperReveal'
import './templates/KineticSpotlightSweep'
import './templates/KineticShutterRoll'
import './templates/KineticPrismSplit'
import './templates/KineticClockWipe'
import './templates/KineticMosaicAssemble'

// ── Geometric Reveals: Mechanical ─────────────────────────────────────
import './templates/KineticGarageDoor'
import './templates/KineticSlidingDoors'
import './templates/KineticRevolvingDoor'
import './templates/KineticBookOpen'
import './templates/KineticFanUnfold'
import './templates/KineticZipperPull'
import './templates/KineticElevatorDoors'
import './templates/KineticTrapdoor'

// ── Mechanical: Everyday Objects ──────────────────────────────────────
import './templates/KineticRollUpBlind'
import './templates/KineticUmbrellaOpen'
import './templates/KineticZipperOpen'
import './templates/KineticSwitchFlip'
import './templates/KineticPopSocket'
import './templates/KineticCoinFlip'
import './templates/KineticDeckShuffle'
import './templates/KineticWindowShade'

// ── Minimal & clean ────────────────────────────────────────────────────
import './templates/KineticMinimalFade'
import './templates/KineticMinimalMask'
import './templates/KineticMinimalRevealLine'
import './templates/KineticMinimalRotate'
import './templates/KineticMinimalSlideUp'
import './templates/KineticMinimalBlur'
import './templates/KineticMinimalWeight'
import './templates/KineticMinimalTracking'
import './templates/KineticMinimalStroke'
import './templates/KineticMinimalSkew'
import './templates/KineticMinimalFlip'
import './templates/KineticMinimalUnderline'
import './templates/KineticMinimalCase'
import './templates/KineticSmoothSlide'
import './templates/KineticMonochrome'
import './templates/KineticPastelDream'
import './templates/KineticEchoFade'
import './templates/KineticGhostFade'
import './templates/KineticInspirationBreath'
import './templates/KineticMantraRepeat'
import './templates/KineticWordByWord'

// ── Minimal Clip-Path Reveals ──────────────────────────────────────────
import './templates/KineticMinimalDiamond'
import './templates/KineticMinimalHex'
import './templates/KineticMinimalStar'
import './templates/KineticMinimalCross'
import './templates/KineticMinimalCurtain'
import './templates/KineticMinimalPolygon'
import './templates/KineticMinimalCircleGrow'
import './templates/KineticMinimalZigzag'

// ── Bold & impact ──────────────────────────────────────────────────────
import './templates/KineticBoldImpact'
import './templates/KineticClapBack'
import './templates/KineticDramaticPause'
import './templates/KineticEpicReveal'
import './templates/KineticImpactMeme'
import './templates/KineticMotivationalSlam'
import './templates/KineticNoCapText'
import './templates/KineticPowerWord'
import './templates/KineticSubtitlePop'

// ── Transitions & reveals ──────────────────────────────────────────────
import './templates/KineticDarkReveal'
import './templates/KineticDoorOpen'
import './templates/KineticFlashTransition'
import './templates/KineticFlipCard'
import './templates/KineticFoldTransition'
import './templates/KineticGlitchTransition'
import './templates/KineticInkDropTransition'
import './templates/KineticLiquidTransition'
import './templates/KineticMorphTransition'
import './templates/KineticPageTurn'
import './templates/KineticPixelateTransition'
import './templates/KineticSlideWipeTransition'
import './templates/KineticStackReveal'
import './templates/KineticTiltReveal'
import './templates/KineticZoomBlurTransition'

// ── Music & audio ──────────────────────────────────────────────────────
import './templates/KineticBassDropPulse'
import './templates/KineticDJDeck'
import './templates/KineticEqualizerBars'
import './templates/KineticKaraokeHighlight'
import './templates/KineticSoundwave'

// ── Tech & data ────────────────────────────────────────────────────────
import './templates/KineticAIGenerate'
import './templates/KineticBinaryStream'
import './templates/KineticCircuitBoard'
import './templates/KineticCodeTerminal'
import './templates/KineticDataStream'
import './templates/KineticHologramScan'
import './templates/KineticHUDDisplay'
import './templates/KineticLoadingBar'
import './templates/KineticWiggleText'

// ── Hacker & Dev Culture ──────────────────────────────────────────────
import './templates/KineticGitDiff'
import './templates/KineticTerminalPrompt'
import './templates/KineticJSONParse'
import './templates/KineticRegexMatch'
import './templates/KineticSyntaxHighlight'
import './templates/KineticDeploySuccess'
import './templates/KineticAPIResponse'
import './templates/KineticMarkdownRender'

// ── Technical drawing & CAD ────────────────────────────────────────────
import './templates/KineticIsometricType'
import './templates/KineticCADTrace'
import './templates/KineticSectionCut'
import './templates/KineticDimensionLine'
import './templates/KineticContourMap'
import './templates/KineticCircuitTrace'
import './templates/KineticSchematic'
import './templates/KineticLaserCut'

// ── Film & cinema ──────────────────────────────────────────────────────
import './templates/KineticCinemaLetterbox'
import './templates/KineticFilmBurn'
import './templates/KineticOpeningCredits'
import './templates/KineticTrailerTitle'
import './templates/KineticVignetteFocus'

// ── Film: Projection & Screen ─────────────────────────────────────────
import './templates/KineticDriveInProject'
import './templates/KineticRearProject'
import './templates/KineticIMAXReveal'
import './templates/KineticCountdownFilm'
import './templates/KineticFilmBurnReveal'
import './templates/KineticCinemaScope'
import './templates/KineticSilentFilmCard'
import './templates/KineticFlickerGate'

// ── Film Camera Effects ────────────────────────────────────────────────
import './templates/KineticRackFocus'
import './templates/KineticDollyZoom'
import './templates/KineticBarrelDistort'
import './templates/KineticFilmGrain'
import './templates/KineticBokehReveal'
import './templates/KineticOverexpose'
import './templates/KineticAnamorphicFlare'
import './templates/KineticPanBlur'

// ── Film: Specific Lens Effects ───────────────────────────────────────
import './templates/KineticTiltShift'
import './templates/KineticSplitDiopter'
import './templates/KineticZoomCrash'
import './templates/KineticLensBreathe'
import './templates/KineticPullFocus'
import './templates/KineticVignetteReveal'
import './templates/KineticNDGradient'
import './templates/KineticLensWhack'

// ── Fashion & lifestyle ────────────────────────────────────────────────
import './templates/KineticFashionEditorial'
import './templates/KineticLuxuryBrand'
import './templates/KineticDuotone'
import './templates/KineticColorShift'
import './templates/KineticGradientFlow'
import './templates/KineticNeonGradient'
import './templates/KineticVogueTitle'
import './templates/KineticRunwayCaption'
import './templates/KineticPerfumeAd'
import './templates/KineticMonogramReveal'
import './templates/KineticCoutureLabel'
import './templates/KineticEditorialSpread'
import './templates/KineticLookbookSlide'
import './templates/KineticBrandManifesto'

// ── Fun & playful ──────────────────────────────────────────────────────
import './templates/KineticBounceWord'
import './templates/KineticBouncyBubble'
import './templates/KineticCarousel'
import './templates/KineticEmojiReaction'
import './templates/KineticFlicker'
import './templates/KineticPartyMode'
import './templates/KineticPopUp'
import './templates/KineticRainbowBounce'
import './templates/KineticRainbowWave'
import './templates/KineticSparkleText'
import './templates/KineticWaveText'

// ── Handmade & craft ───────────────────────────────────────────────────
import './templates/KineticCrawlingText'
import './templates/KineticCrayonDraw'
import './templates/KineticHandwritten'
import './templates/KineticHighlighter'
import './templates/KineticPostItNote'
import './templates/KineticScratched'
import './templates/KineticScribble'
import './templates/KineticSketchyCircle'
import './templates/KineticStampPress'
import './templates/KineticStickyLabel'
import './templates/KineticTornPaper'
import './templates/KineticWhiteboardDraw'

// ── Decorative & borders ───────────────────────────────────────────────
import './templates/KineticGlowBorder'
import './templates/KineticNeonSignBorder'
import './templates/KineticOutlineStroke'
import './templates/KineticParticleFrame'
import './templates/KineticSplitLine'
import './templates/KineticRatioText'

// ── Seasonal & holiday ─────────────────────────────────────────────────
import './templates/KineticBloodSplatter'
import './templates/KineticChristmasSnow'
import './templates/KineticHalloweenSpooky'
import './templates/KineticMysticText'

// ── 3D & perspective ───────────────────────────────────────────────────
import './templates/KineticCubeRotate'
import './templates/KineticParallaxLayers'
import './templates/KineticPerfectScale'
import './templates/KineticPerspectiveZoom'

// ── Scene layout templates ─────────────────────────────────────────────
import './templates/SceneTitleCard'
import './templates/SceneLowerThird'
import './templates/SceneQuoteCard'
import './templates/SceneCallToAction'
import './templates/SceneEndScreen'
import './templates/SceneStatCounter'
import './templates/SceneListReveal'
import './templates/SceneSplitScreen'
import './templates/SceneCountdown'
import './templates/SceneComparison'
import './templates/SceneProcessTimeline'
import './templates/SceneProgressBar'
import './templates/SceneNotification'
import './templates/SceneSocialProof'
import './templates/SceneFeatureShowcase'
import './templates/SceneTestimonial'

// ── Data visualization scenes ──────────────────────────────────────────
import './templates/SceneNumberCounter'
import './templates/SceneBarChart'
import './templates/ScenePieChart'
import './templates/SceneProgressRing'
import './templates/SceneComparisonStat'
import './templates/ScenePercentageBar'
import './templates/SceneRankingList'
import './templates/SceneGrowthArrow'
import './templates/SceneFunnelChart'
import './templates/SceneScoreCard'
import './templates/SceneBudgetBreakdown'
import './templates/SceneBudgetPlan'
import './templates/SceneCryptoPrice'
import './templates/SceneDebtPayoff'
import './templates/SceneInvestmentReturn'
import './templates/SceneMortgageCalc'
import './templates/ScenePortfolioBreakdown'
import './templates/ScenePricingCard'
import './templates/SceneProfitLoss'
import './templates/SceneSavingsGoal'
import './templates/SceneStockTicker'
import './templates/SceneTaxTip'

// ── Social media & messaging scenes ────────────────────────────────────
import './templates/SceneSocialPost'
import './templates/SceneTweetCard'
import './templates/SceneRedditPost'
import './templates/SceneSlackMessage'
import './templates/SceneWhatsApp'
import './templates/SceneDiscordChat'
import './templates/SceneInstagramDM'
import './templates/SceneTextMessage'
import './templates/SceneChatBubble'
import './templates/SceneCommentPrompt'
import './templates/SceneEmailPreview'
import './templates/SceneDuetInvite'
import './templates/SceneFollowMe'
import './templates/SceneLikeSubscribe'
import './templates/SceneShareCTA'
import './templates/SceneStitchPrompt'
import './templates/SceneSwipeUp'
import './templates/SceneTagFriend'

// ── Hook & engagement scenes ───────────────────────────────────────────
import './templates/SceneHookChallenge'
import './templates/SceneHookContrarian'
import './templates/SceneHookControversial'
import './templates/SceneHookListicle'
import './templates/SceneHookMyth'
import './templates/SceneHookNumber'
import './templates/SceneHookQuestion'
import './templates/SceneHookSecret'
import './templates/SceneHookStory'
import './templates/SceneHookUrgent'
import './templates/ScenePOV'
import './templates/SceneExpandingBrain'
import './templates/SceneDrakeFormat'
import './templates/SceneRedFlag'
import './templates/SceneStarterPack'
import './templates/SceneThisOrThat'
import './templates/SceneTierList'
import './templates/SceneMythBuster'

// ── Food & cooking scenes ──────────────────────────────────────────────
import './templates/SceneCookingStep'
import './templates/SceneCookingTimer'
import './templates/SceneFoodRating'
import './templates/SceneIngredientList'
import './templates/SceneMacroTracker'
import './templates/SceneMealPlan'
import './templates/SceneMealPrep'
import './templates/SceneNutritionFacts'
import './templates/SceneRecipeCard'
import './templates/SceneRecipeTitle'

// ── Fitness & health scenes ────────────────────────────────────────────
import './templates/SceneExerciseDemo'
import './templates/SceneFitnessTracker'
import './templates/SceneGoalTracker'
import './templates/SceneHealthBar'
import './templates/SceneHeartRateZone'
import './templates/ScenePersonalRecord'
import './templates/SceneStepCounter'
import './templates/SceneSupplementStack'
import './templates/SceneWorkoutCard'
import './templates/SceneWorkoutTimer'
import './templates/SceneProgressTransform'

// ── E-commerce & shopping scenes ───────────────────────────────────────
import './templates/SceneCartSummary'
import './templates/SceneCouponCode'
import './templates/SceneFlashSale'
import './templates/SceneProductCard'
import './templates/SceneProductReveal'
import './templates/SceneProductReview'
import './templates/SceneProductReviewBeauty'
import './templates/ScenePriceReduction'
import './templates/SceneSalesBanner'
import './templates/SceneShippingTracker'
import './templates/SceneShopMyLook'
import './templates/SceneSizeGuide'
import './templates/SceneWishlistItem'

// ── Real estate scenes ─────────────────────────────────────────────────
import './templates/SceneJustSold'
import './templates/SceneNeighborhoodGuide'
import './templates/SceneOpenHouse'
import './templates/ScenePropertyListing'
import './templates/ScenePropertyStats'

// ── Travel & adventure scenes ──────────────────────────────────────────
import './templates/SceneAdventureStats'
import './templates/SceneCountdownToTrip'
import './templates/SceneDestinationCard'
import './templates/SceneFlightBoard'
import './templates/SceneHotelReview'
import './templates/ScenePackingList'
import './templates/ScenePhrasebook'
import './templates/SceneTravelDestination'
import './templates/SceneTravelItinerary'
import './templates/SceneTravelTip'

// ── Entertainment & media scenes ───────────────────────────────────────
import './templates/SceneHighlightReel'
import './templates/SceneMovieRating'
import './templates/SceneMovieTrailer'
import './templates/SceneMusicPlayer'
import './templates/SceneNowPlaying'
import './templates/ScenePlaylistCard'
import './templates/ScenePodcastCard'
import './templates/ScenePodcastEpisode'
import './templates/ScenePodcastQuote'
import './templates/SceneStreamOverlay'
import './templates/SceneTVShowBumper'
import './templates/SceneYouTubeEndScreen'
import './templates/SceneLyricsCard'
import './templates/SceneConcertPoster'
import './templates/SceneFilmCreditsRoll'
import './templates/SceneDirectorSlate'

// ── Gaming scenes ──────────────────────────────────────────────────────
import './templates/SceneAchievementUnlock'
import './templates/SceneGameOver'
import './templates/SceneGameRecap'
import './templates/SceneGameTimer'
import './templates/SceneLeaderboard'
import './templates/SceneLevelUp'
import './templates/SceneLootDrop'
import './templates/SceneScoreboard'

// ── Sports scenes ──────────────────────────────────────────────────────
import './templates/SceneMatchScore'
import './templates/SceneMatchup'
import './templates/ScenePlayerCard'
import './templates/SceneSportsScore'
import './templates/SceneStandingsTable'
import './templates/SceneVersusScreen'

// ── Education & learning scenes ────────────────────────────────────────
import './templates/SceneAlphabetLetter'
import './templates/SceneDefinition'
import './templates/SceneElementCard'
import './templates/SceneFactReveal'
import './templates/SceneFlashCard'
import './templates/ScenePlanetCard'
import './templates/SceneQuizQuestion'
import './templates/SceneQuizTimer'
import './templates/SceneTutorialStep'

// ── Beauty & fashion scenes ────────────────────────────────────────────
import './templates/SceneGetReadyWithMe'
import './templates/SceneHairTutorial'
import './templates/SceneOOTD'
import './templates/SceneSkincareRoutine'
import './templates/SceneTrendAlert'
import './templates/SceneColorPalette'

// ── Astrology & spiritual scenes ───────────────────────────────────────
import './templates/SceneCompatibility'
import './templates/SceneHoroscope'
import './templates/SceneTarotCard'
import './templates/SceneZodiacSign'

// ── Pet & animal scenes ────────────────────────────────────────────────
import './templates/SceneAdoptMe'
import './templates/ScenePetFact'
import './templates/ScenePetProfile'

// ── Events & celebrations scenes ───────────────────────────────────────
import './templates/SceneBirthdayCard'
import './templates/SceneEventPromo'
import './templates/SceneEventSchedule'
import './templates/SceneSaveTheDate'
import './templates/SceneWeddingInvite'
import './templates/SceneNewYearCountdown'

// ── DIY & craft scenes ─────────────────────────────────────────────────
import './templates/SceneCraftSupply'
import './templates/SceneDIYStep'
import './templates/SceneDIYSupplies'

// ── Crypto & finance scenes ────────────────────────────────────────────
import './templates/SceneCryptoAlert'

// ── Eco & sustainability scenes ────────────────────────────────────────
import './templates/SceneCarbonFootprint'

// ── Timers & countdowns ────────────────────────────────────────────────
import './templates/SceneCircularTimer'
import './templates/SceneDailyCountdown'
import './templates/SceneFlipClock'
import './templates/SceneLaunchCountdown'
import './templates/SceneMinimalCountdown'
import './templates/SceneMotivationalCounter'
import './templates/SceneOfferCountdown'
import './templates/ScenePomodoroTimer'
import './templates/SceneProgressCountdown'

// ── Minimal scenes ─────────────────────────────────────────────────────
import './templates/SceneMinimalEndCard'
import './templates/SceneMinimalGrid'
import './templates/SceneMinimalNumber'
import './templates/SceneMinimalQuote'
import './templates/SceneMinimalSplit'

// ── UI & layout scenes ─────────────────────────────────────────────────
import './templates/SceneAnnouncementBanner'
import './templates/SceneAppShowcase'
import './templates/SceneBadgeSticker'
import './templates/SceneBeforeAfter'
import './templates/SceneBrandIntro'
import './templates/SceneBreakingNews'
import './templates/SceneChapterTitle'
import './templates/SceneCornerAccent'
import './templates/SceneDiagramFlow'
import './templates/SceneFeatureHighlight'
import './templates/SceneFrameBorder'
import './templates/SceneNewsAlert'
import './templates/SceneNewsLowerThird'
import './templates/SceneNewsTicker'
import './templates/SceneNotificationBell'
import './templates/ScenePolaroidFrame'
import './templates/SceneRibbonBanner'
import './templates/SceneStickerPack'
import './templates/SceneTimelineHorizontal'
import './templates/SceneVintageBorder'

// ── Lifestyle & wellness scenes ────────────────────────────────────────
import './templates/SceneAffirmation'
import './templates/SceneBookReview'
import './templates/SceneDailyRoutine'
import './templates/SceneJournalEntry'
import './templates/SceneMoodBoard'
import './templates/SceneVisionBoard'
import './templates/SceneWisdomCard'

// ── Interactive & poll scenes ──────────────────────────────────────────
import './templates/SceneEmojiPoll'
import './templates/SceneEmojiRain'
import './templates/ScenePollQuestion'
import './templates/SceneReactionBar'

// ── Informational scenes ───────────────────────────────────────────────
import './templates/SceneProConList'
import './templates/SceneQuoteWithAuthor'
import './templates/SceneStepByStep'
import './templates/SceneTestimonialCard'

// ── Weather scenes ─────────────────────────────────────────────────────
import './templates/SceneWeatherCard'

// ── Tech & glitch kinetic ──────────────────────────────────────────────
import './templates/KineticGlitchMatrix'

// ═══════════════════════════════════════════════════════════════════════
// Wave 4 Templates (19 categories × 17 templates = 323 new)
// ═══════════════════════════════════════════════════════════════════════

// ── Meditation & Mindfulness ───────────────────────────────────────────
import './templates/KineticZenBreath'
import './templates/KineticMeditationBell'
import './templates/KineticLotusBloom'
import './templates/KineticChakraGlow'
import './templates/KineticMandalaReveal'
import './templates/KineticZenGarden'
import './templates/SceneMeditationTimer'
import './templates/SceneChakraChart'
import './templates/SceneBreathingExercise'
import './templates/SceneMindfulnessQuote'
import './templates/SceneGratitudeJournal'
import './templates/SceneSleepScore'
import './templates/SceneStressLevel'
import './templates/SceneMoodTracker'
import './templates/SceneYogaPose'
import './templates/SceneAffirmationCard'
import './templates/SceneSoundBath'

// ── Retro Gaming & Arcade ──────────────────────────────────────────────
import './templates/KineticArcadeInsertCoin'
import './templates/KineticPixelExplosion'
import './templates/KineticGameOverFlicker'
import './templates/KineticPlatformerBounce'
import './templates/KineticSpaceInvader'
import './templates/SceneArcadeHighScore'
import './templates/SceneRetroAchievement'
import './templates/ScenePixelHealthBar'
import './templates/ScenePowerUpCollect'
import './templates/SceneRetroLoadScreen'
import './templates/SceneGameControllerGuide'
import './templates/SceneRetroScoreboard'
import './templates/ScenePixelMap'
import './templates/SceneBossHealthBar'
import './templates/SceneInventoryGrid'
import './templates/SceneDialogueBox'
import './templates/SceneQuestLog'

// ── Photography & Camera ───────────────────────────────────────────────
import './templates/KineticShutterClick'
import './templates/KineticLensFlare'
import './templates/KineticDarkroom'
import './templates/KineticViewfinder'
import './templates/ScenePhotoExif'
import './templates/SceneLightbox'
import './templates/SceneCameraSetting'
import './templates/ScenePhotoComparison'
import './templates/SceneColorGrading'
import './templates/SceneHistogram'
import './templates/SceneLensCard'
import './templates/ScenePhotoChallenge'
import './templates/SceneGoldenRatio'
import './templates/SceneFilmRoll'
import './templates/ScenePhotoAward'
import './templates/SceneExposureTriangle'

// ── Architecture & Interior ────────────────────────────────────────────
import './templates/KineticBlueprintReveal'
import './templates/KineticGridArchitect'
import './templates/KineticConcreteTexture'
import './templates/KineticNeonFloorplan'
import './templates/KineticMarbleVein'
import './templates/SceneFloorPlan'
import './templates/SceneRoomMoodBoard'
import './templates/SceneColorScheme'
import './templates/SceneFurnitureSpec'
import './templates/SceneBuildingStats'
import './templates/SceneRenovationBudget'
import './templates/ScenePropertyTour'
import './templates/SceneMaterialSwatch'
import './templates/SceneArchitectProfile'
import './templates/SceneSustainableHome'
import './templates/SceneSmartHomeControl'
import './templates/SceneLightingPlan'

// ── Auto & Motorsport ──────────────────────────────────────────────────
import './templates/KineticSpeedometer'
import './templates/KineticRacingStripe'
import './templates/KineticNitroBoost'
import './templates/KineticTireSkid'
import './templates/KineticDashboard'
import './templates/SceneCarSpecCard'
import './templates/SceneRaceLeaderboard'
import './templates/SceneLapTimer'
import './templates/SceneGarageShowroom'
import './templates/SceneCarComparison'
import './templates/SceneFuelGauge'
import './templates/SceneServiceLog'
import './templates/SceneRaceCalendar'
import './templates/SceneCarReview'
import './templates/SceneParkingGuide'
import './templates/SceneTrafficUpdate'
import './templates/SceneEVChargingStatus'

// ── Music & Festival ───────────────────────────────────────────────────
import './templates/KineticRecordSpin'
import './templates/KineticAmplifierDrive'
import './templates/KineticFestivalNeon'
import './templates/KineticMixerFader'
import './templates/KineticWaveformText'
import './templates/SceneAlbumCard'
import './templates/SceneSetlistCard'
import './templates/SceneFestivalLineup'
import './templates/SceneSongLyricSync'
import './templates/SceneGenreMeter'
import './templates/SceneBPMCounter'
import './templates/SceneArtistProfile'
import './templates/SceneMusicChartRank'
import './templates/SceneTunerDisplay'
import './templates/SceneMixingDesk'
import './templates/SceneVenueMap'
import './templates/SceneTicketStub'

// ── Science & Laboratory ───────────────────────────────────────────────
import './templates/KineticDNAHelix'
import './templates/KineticAtomOrbit'
import './templates/KineticChemicalReaction'
import './templates/KineticMicroscope'
import './templates/KineticLabBeaker'
import './templates/ScenePeriodicElement'
import './templates/SceneMoleculeModel'
import './templates/SceneLabResult'
import './templates/SceneChemicalEquation'
import './templates/SceneResearchPaper'
import './templates/SceneExperimentStep'
import './templates/SceneMicroscopeSlide'
import './templates/SceneScientistProfile'
import './templates/SceneSpaceExplorer'
import './templates/SceneSatelliteTracker'
import './templates/SceneWeatherStation'
import './templates/SceneGeologyLayer'

// ── Kids & Cartoon ─────────────────────────────────────────────────────
import './templates/KineticCrayonWrite'
import './templates/KineticBalloonFloat'
import './templates/KineticJellyWobble'
import './templates/KineticStarBurst'
import './templates/KineticBubblePop'
import './templates/SceneSpellingBee'
import './templates/SceneColorWheel'
import './templates/SceneAnimalFact'
import './templates/SceneCountingGame'
import './templates/SceneStoryTime'
import './templates/SceneRewardChart'
import './templates/SceneABCCard'
import './templates/SceneMathProblem'
import './templates/SceneShapeLearn'
import './templates/SceneKidsRecipe'
import './templates/SceneBedtimeRoutine'
import './templates/SceneChoreTracker'

// ── Horror & Creepy ────────────────────────────────────────────────────
import './templates/KineticBloodDrool'
import './templates/KineticGhostFlicker'
import './templates/KineticSpiderCrawl'
import './templates/KineticZombieRise'
import './templates/KineticHauntedType'
import './templates/SceneCreepyCountdown'
import './templates/SceneGhostStory'
import './templates/SceneHorrorMovieCard'
import './templates/SceneParanormalMeter'
import './templates/SceneCrimeScene'
import './templates/SceneOutijaBoard'
import './templates/SceneCreepyPasta'
import './templates/SceneHauntedHouse'
import './templates/SceneMysteryClue'
import './templates/SceneScareRating'
import './templates/SceneSurvivalGuide'
import './templates/SceneMonsterProfile'

// ── Marketing & Business ───────────────────────────────────────────────
import './templates/KineticROICounter'
import './templates/KineticBrandReveal'
import './templates/KineticSalesBanner'
import './templates/KineticTestimonialSlide'
import './templates/KineticCTAFlash'
import './templates/SceneKPIDashboard'
import './templates/SceneConversionFunnel'
import './templates/SceneABTestResult'
import './templates/SceneROICalculator'
import './templates/SceneCompetitorMatrix'
import './templates/SceneSocialMetrics'
import './templates/SceneCampaignTimeline'
import './templates/SceneEmailStats'
import './templates/SceneSEOScore'
import './templates/SceneCustomerJourney'
import './templates/SceneBrandGuideline'
import './templates/SceneMarketShare'

// ── Food & Restaurant ──────────────────────────────────────────────────
import './templates/KineticMenuChalk'
import './templates/KineticSizzlePop'
import './templates/KineticNeonDiner'
import './templates/KineticFoodStamp'
import './templates/KineticCoffeeStain'
import './templates/SceneMenuBoard'
import './templates/SceneRestaurantReview'
import './templates/SceneWineCard'
import './templates/SceneCocktailRecipe'
import './templates/SceneCalorieBreakdown'
import './templates/SceneFoodDelivery'
import './templates/SceneTableReservation'
import './templates/SceneChefProfile'
import './templates/SceneFoodTruckMenu'
import './templates/SceneBakeryOrder'
import './templates/SceneBreweryTap'
import './templates/SceneSeasonalMenu'

// ── Social Media Creator ───────────────────────────────────────────────
import './templates/KineticHashtagDrop'
import './templates/KineticViralSpread'
import './templates/KineticStoryCaptions'
import './templates/KineticReelsTransition'
import './templates/KineticTrendingUp'
import './templates/SceneFollowerMilestone'
import './templates/SceneContentCalendar'
import './templates/SceneAnalyticsDashboard'
import './templates/SceneCollabAnnounce'
import './templates/SceneGiveawayCard'
import './templates/SceneLinkInBio'
import './templates/SceneSponsoredPost'
import './templates/SceneFanArtShowcase'
import './templates/SceneMerchDrop'
import './templates/SceneStreamSchedule'
import './templates/SceneCreatorTip'
import './templates/SceneViralChallenge'

// ── Vintage & Retro Aesthetic ──────────────────────────────────────────
import './templates/KineticSepia'
import './templates/KineticOldFilm'
import './templates/KineticNoir'
import './templates/KineticRetroTV'
import './templates/KineticVintagePostcard'
import './templates/KineticGildedAge'
import './templates/SceneVintageLabel'
import './templates/SceneRetroAd'
import './templates/SceneVintageReceipt'
import './templates/SceneFilmPoster'
import './templates/SceneRetroNewspaper'
import './templates/SceneVintageMenu'
import './templates/SceneRetroTV'
import './templates/SceneGramophone'
import './templates/SceneVintageLetter'
import './templates/SceneRetroPostcard'
import './templates/SceneOldRadio'

// ── Space & Astronomy ──────────────────────────────────────────────────
import './templates/KineticStarWarp'
import './templates/KineticNebulaGlow'
import './templates/KineticCosmicDust'
import './templates/KineticBlackHole'
import './templates/KineticAsteroidField'
import './templates/SceneConstellationMap'
import './templates/SceneSolarSystem'
import './templates/SceneMoonPhase'
import './templates/SceneRocketLaunch'
import './templates/SceneAstronautProfile'
import './templates/SceneTelescopeView'
import './templates/SceneSpaceWeather'
import './templates/ScenePlanetFact'
import './templates/SceneSatelliteOrbit'
import './templates/SceneMarsBase'
import './templates/SceneStarChart'
import './templates/SceneNightSkyGuide'

// ── Eco & Sustainability ───────────────────────────────────────────────
import './templates/KineticLeafSwirl'
import './templates/KineticEarthPulse'
import './templates/KineticRecycleFlow'
import './templates/KineticSolarFlare'
import './templates/KineticOceanClean'
import './templates/SceneEcoScore'
import './templates/SceneWaterUsage'
import './templates/SceneEnergyBreakdown'
import './templates/ScenePlantGrowth'
import './templates/SceneRecyclingGuide'
import './templates/SceneAirQuality'
import './templates/SceneElectricVehicle'
import './templates/SceneGardenPlanner'
import './templates/SceneCompostGuide'
import './templates/SceneClimateAction'
import './templates/SceneTreeCounter'
import './templates/SceneZeroWasteGoal'

// ── Cyberpunk & Futuristic ─────────────────────────────────────────────
import './templates/KineticHolographic'
import './templates/KineticNeuralNet'
import './templates/KineticDigitalRain'
import './templates/KineticCyberSlice'
import './templates/KineticAugmentedReality'
import './templates/SceneCyberProfile'
import './templates/SceneFutureCity'
import './templates/SceneHologramDisplay'
import './templates/SceneQuantumComputer'
import './templates/SceneNeuralInterface'
import './templates/SceneRobotStatus'
import './templates/SceneVROverlay'
import './templates/SceneBlockchainBlock'
import './templates/SceneAIStatus'
import './templates/SceneCyborgUpgrade'
import './templates/SceneFutureForecast'
import './templates/SceneDigitalPassport'

// ── Fitness & Gym ──────────────────────────────────────────────────────
import './templates/KineticGymPump'
import './templates/KineticSweatDrip'
import './templates/KineticWeightSlam'
import './templates/KineticPulseBeat'
import './templates/KineticFireRep'
import './templates/SceneGymProgram'
import './templates/SceneMaxLift'
import './templates/SceneBodyMeasure'
import './templates/SceneCalorieBurn'
import './templates/SceneSupplementPlan'
import './templates/SceneSplitSchedule'
import './templates/SceneFormCheck'
import './templates/SceneRunTracker'
import './templates/SceneSwimLap'
import './templates/SceneCyclingRoute'
import './templates/SceneClassSchedule'
import './templates/SceneMembershipCard'

// ── Book & Literature ──────────────────────────────────────────────────
import './templates/KineticPageFlutter'
import './templates/KineticInkQuill'
import './templates/KineticLibraryShelf'
import './templates/KineticParchmentScroll'
import './templates/KineticBookmarkSlide'
import './templates/SceneBookCover'
import './templates/SceneReadingList'
import './templates/SceneBookClubPick'
import './templates/SceneAuthorProfile'
import './templates/SceneBookQuote'
import './templates/SceneReadingChallenge'
import './templates/SceneGenreGuide'
import './templates/ScenePageTracker'
import './templates/SceneLibraryCard'
import './templates/SceneBookshelf'
import './templates/SceneWritingPrompt'
import './templates/ScenePoetryCard'

// ── Weather & Climate ──────────────────────────────────────────────────
import './templates/KineticLightningStrike'
import './templates/KineticBlizzard'
import './templates/KineticRainbowArc'
import './templates/KineticTornadoSpin'
import './templates/KineticHeatWave'
import './templates/SceneWeatherForecast'
import './templates/SceneTemperatureMap'
import './templates/SceneWindSpeed'
import './templates/SceneUVIndex'
import './templates/ScenePollenCount'
import './templates/SceneHumidityGauge'
import './templates/SceneSunriseSunset'
import './templates/SceneTideChart'
import './templates/SceneAvalancheRisk'
import './templates/SceneStormTracker'
import './templates/SceneSeasonalClock'
import './templates/SceneClimateGraph'

// ── Final Batch (800 milestone) ────────────────────────────────────────
import './templates/KineticGradientMesh'
import './templates/KineticSoapBubble'
import './templates/KineticOrigami'
import './templates/KineticSandwriting'
import './templates/SceneUnboxing'
import './templates/SceneRoomTour'
import './templates/ScenePetAdoption'
import './templates/ScenePlantCare'
import './templates/SceneGroceryList'
import './templates/SceneBucketList'
import './templates/SceneMovieNight'
import './templates/ScenePlaydate'
import './templates/SceneFitnessMilestone'
import './templates/SceneSeasonalGreeting'
import './templates/SceneDailyHabit'
import './templates/SceneMemoryCard'

// ═══════════════════════════════════════════════════════════════════════
// Round 2 Templates (analysis-driven, 136 templates)
// ═══════════════════════════════════════════════════════════════════════

// ── Print & Letterpress (Round 2) ─────────────────────────────────────
import './templates/KineticDeboss'
import './templates/KineticEngraving'
import './templates/KineticFoilStamp'
import './templates/KineticLetterpress'
import './templates/KineticMonoprint'
import './templates/KineticProofMark'
import './templates/KineticRisograph'
import './templates/KineticScreenPrint'
import './templates/KineticWaxSeal'

// ── Film & Cinema (Round 2) ───────────────────────────────────────────
import './templates/KineticBlaxploitation'
import './templates/KineticDriveIn'
import './templates/KineticFilmLeader'
import './templates/KineticFilmNoir'
import './templates/KineticGodRays'
import './templates/KineticKenBurns'
import './templates/KineticLightLeak'
import './templates/KineticMicrofiche'
import './templates/KineticOverheadProjector'
import './templates/KineticProjectorBeam'
import './templates/KineticSilentFilm'
import './templates/KineticSlideProjector'
import './templates/KineticSubtitleBurn'
import './templates/KineticVHSRewind'

// ── Digital Corruption (Round 2) ──────────────────────────────────────
import './templates/KineticAutocomplete'
import './templates/KineticBarcodeReveal'
import './templates/KineticBufferOverflow'
import './templates/KineticDataCorrupt'
import './templates/KineticErrorLog'
import './templates/KineticLoadingDots'
import './templates/KineticPacketLoss'
import './templates/KineticQRDecode'
import './templates/KineticSearchQuery'
import './templates/KineticSignalLoss'

// ── Glitch Corruption II: Software Failure Modes ──────────────────────
import './templates/KineticFontCorrupt'
import './templates/KineticEncodingError'
import './templates/KineticMemoryLeak'
import './templates/KineticStackOverflow'
import './templates/KineticKernelPanic'
import './templates/KineticSegfault'
import './templates/KineticNullPointer'
import './templates/KineticRaceCondition'

// ── Broadcast & TV (Round 2) ──────────────────────────────────────────
import './templates/KineticAirportFlap'
import './templates/KineticBillboardPeel'
import './templates/KineticBreakingBanner'
import './templates/KineticChannelBug'
import './templates/KineticClosedCaption'
import './templates/KineticHighwaySign'
import './templates/KineticLowerThirdNews'
import './templates/KineticMarqueeScroll'
import './templates/KineticSportsScore'
import './templates/KineticTeleprompter'
import './templates/KineticTeletext'
import './templates/KineticTickerTape'
import './templates/KineticWeatherCrawl'

// ── Editorial & Typography (Round 2) ──────────────────────────────────
import './templates/KineticColophon'
import './templates/KineticDropCap'
import './templates/KineticFootnote'
import './templates/KineticMarginNote'
import './templates/KineticPullQuote'
import './templates/KineticRedaction'
import './templates/KineticRunningHead'

// ── Magazine & Editorial ───────────────────────────────────────────────
import './templates/KineticCoverLine'
import './templates/KineticPullQuoteCallout'
import './templates/KineticMagazineFold'
import './templates/KineticEditorialGrid'
import './templates/KineticMastheadReveal'
import './templates/KineticBylineSlide'
import './templates/KineticDropCapAnimate'
import './templates/KineticColumnFlow'

// ── Text Distortion & Destruction (Round 2) ───────────────────────────
import './templates/KineticAnamorphicSqueeze'
import './templates/KineticBurnAway'
import './templates/KineticDisintegrate'
import './templates/KineticErosion'
import './templates/KineticExplodeReform'
import './templates/KineticFisheyeLens'
import './templates/KineticMeltDrip'
import './templates/KineticMirrorReflect'
import './templates/KineticPerspectiveFloor'
import './templates/KineticSandBlast'
import './templates/KineticShatterGlass'
import './templates/KineticShredder'
import './templates/KineticUnravel'

// ── Craft & Tactile (Round 2) ─────────────────────────────────────────
import './templates/KineticCassetteLabel'
import './templates/KineticMagnetLetter'
import './templates/KineticOrigamiFold'
import './templates/KineticPolaroidCaption'
import './templates/KineticReceiptPrint'
import './templates/KineticStampCollection'
import './templates/KineticStickerPeel'
import './templates/KineticStitchThread'
import './templates/KineticTapeLabel'

// ── Gaming & RPG (Round 2) ────────────────────────────────────────────
import './templates/KineticAchievementPop'
import './templates/KineticBossIntro'
import './templates/KineticDamageNumber'
import './templates/KineticLevelUpBurst'
import './templates/KineticQuestUpdate'
import './templates/KineticRPGDialogue'
import './templates/KineticRespawnText'
import './templates/KineticVictoryRoyale'

// ── Miscellaneous Kinetic (Round 2) ───────────────────────────────────
import './templates/KineticASCIIArt'
import './templates/KineticAmiga'
import './templates/KineticBBS'
import './templates/KineticBlacklight'
import './templates/KineticCafeChalk'
import './templates/KineticCaptchaDistort'
import './templates/KineticCaptchaType'
import './templates/KineticChurchSign'
import './templates/KineticCondensation'
import './templates/KineticCountdownClock'
import './templates/KineticDOS'
import './templates/KineticDotMatrixPrinter'
import './templates/KineticEtchASketch'
import './templates/KineticFrostBite'
import './templates/KineticJigsawAssemble'
import './templates/KineticLavaLamp'
import './templates/KineticMercuryBlob'
import './templates/KineticNeonFlicker'
import './templates/KineticNeonTube'
import './templates/KineticOSXLeopard'
import './templates/KineticOilSlick'
import './templates/KineticPaintPour'
import './templates/KineticRolodex'
import './templates/KineticRubberBand'
import './templates/KineticShadowPuppet'
import './templates/KineticSmokeCurl'
import './templates/KineticStrobePulse'
import './templates/KineticSubwayTile'
import './templates/KineticSunDial'
import './templates/KineticThermalVision'
import './templates/KineticWaterDrop'
import './templates/KineticWin95Dialog'
import './templates/KineticXRayScan'

// ── Social & Messaging Scenes (Round 2) ───────────────────────────────
import './templates/SceneDiscordMessage'
import './templates/SceneHackerNewsPost'
import './templates/SceneLinkedInPost'
import './templates/SceneRedditComment'
import './templates/SceneSignalMessage'
import './templates/SceneSubstackQuote'
import './templates/SceneYouTubeComment'
import './templates/SceneiMessageBubble'

// ── Internet Culture Scenes (Round 2) ─────────────────────────────────
import './templates/Scene404Error'
import './templates/SceneCookieConsent'
import './templates/SceneLoadingScreen'
import './templates/SceneTermsOfService'

// ── Text-Centric Scenes (Round 2) ─────────────────────────────────────
import './templates/SceneAcademicCitation'
import './templates/SceneBusinessCard'
import './templates/SceneDedicationPage'
import './templates/SceneEpigraph'
import './templates/ScenePoetryVerse'
import './templates/ScenePostcard'
import './templates/SceneReceipt'
import './templates/SceneScreenplay'

// ── Round 3: Darkroom & Photochemical ────────────────────────────────
import './templates/KineticChromatic'
import './templates/KineticContactSheet'
import './templates/KineticCyanotype'
import './templates/KineticDaguerreotype'
import './templates/KineticDeveloperBath'
import './templates/KineticDoubleExposure'
import './templates/KineticPhotogram'
import './templates/KineticSolarize'

// ── Round 3: Mechanical Printing & Reproduction ──────────────────────
import './templates/KineticFlexography'
import './templates/KineticGelliPlate'
import './templates/KineticHotFoil'
import './templates/KineticIntaglio'
import './templates/KineticLinocut'
import './templates/KineticLithograph'
import './templates/KineticMimeograph'
import './templates/KineticWoodType'

// ── Round 3: Industrial Warning & Safety ─────────────────────────────
import './templates/KineticBiohazard'
import './templates/KineticBlackBox'
import './templates/KineticCautionStripe'
import './templates/KineticExitSign'
import './templates/KineticFloorMarking'
import './templates/KineticHazardTape'
import './templates/KineticHighVoltage'
import './templates/KineticRadioactive'

// ── Round 3: Paper, Document & Mail ──────────────────────────────────
import './templates/KineticAirmailStripe'
import './templates/KineticBlueprintAmmonia'
import './templates/KineticCarbonCopy'
import './templates/KineticFaxMachine'
import './templates/KineticOnionskin'
import './templates/KineticTelegram'
import './templates/KineticThermalFade'
import './templates/KineticTracingPaper'

// ── Round 3: Medical & Scientific Instruments ────────────────────────
import './templates/KineticDNASequence'
import './templates/KineticEKGTrace'
import './templates/KineticLabNotebook'
import './templates/KineticMicroscopeZoom'
import './templates/KineticMolecularBond'
import './templates/KineticPeriodicFlash'
import './templates/KineticPulseOx'
import './templates/KineticSpectrometer'

// ── Round 3: Cartography & Navigation ────────────────────────────────
import './templates/KineticCompassBearing'
import './templates/KineticFlightPath'
import './templates/KineticGPSLock'
import './templates/KineticNauticalChart'
import './templates/KineticStarNavigate'
import './templates/KineticSubwayRoute'
import './templates/KineticTopographic'
import './templates/KineticTreasureMap'

// ── Round 3: Decay, Aging & Patina ───────────────────────────────────
import './templates/KineticCrackedGlaze'
import './templates/KineticFoxing'
import './templates/KineticPaintPeel'
import './templates/KineticRustCorrosion'
import './templates/KineticSunBleach'
import './templates/KineticTapeResidue'
import './templates/KineticVerdigris'
import './templates/KineticWaterDamage'

// ── Round 3: Signal Processing & Audio FX ────────────────────────────
import './templates/KineticBitCrush'
import './templates/KineticFreqModulate'
import './templates/KineticGranular'
import './templates/KineticNoiseGate'
import './templates/KineticPhaseDistort'
import './templates/KineticRingMod'
import './templates/KineticSampleHold'
import './templates/KineticSineWave'

// ── Round 3: Musical Notation & Performance ──────────────────────────
import './templates/KineticConductorBaton'
import './templates/KineticDynamicsMark'
import './templates/KineticFermataHold'
import './templates/KineticGlissandoSweep'
import './templates/KineticMetronomeTick'
import './templates/KineticSheetMusic'
import './templates/KineticStaccatoDot'
import './templates/KineticTrebleClef'

// ── Round 3: Textile & Fabric Craft ──────────────────────────────────
import './templates/KineticBatikCrack'
import './templates/KineticBlockPrint'
import './templates/KineticCrossStitch'
import './templates/KineticEmbroideryHoop'
import './templates/KineticKnitted'
import './templates/KineticLoomWeave'
import './templates/KineticQuiltPatch'
import './templates/KineticTieDye'

// ── Round 3: Glass, Optics & Reflection ──────────────────────────────
import './templates/KineticFiberOptic'
import './templates/KineticFrostedGlass'
import './templates/KineticKaleidoscope'
import './templates/KineticMagnifyGlass'
import './templates/KineticMirrorCrack'
import './templates/KineticPrismRefract'
import './templates/KineticRaindropLens'
import './templates/KineticStainedGlass'

// ── Round 3: Material & Surface Processes ────────────────────────────
import './templates/KineticCeramicGlaze'
import './templates/KineticConcreteStamp'
import './templates/KineticFabricDye'
import './templates/KineticGlassEtch'
import './templates/KineticLeatherStamp'
import './templates/KineticMetalEngrave'
import './templates/KineticStoneCarve'
import './templates/KineticWoodBurn'

// ── Round 3: Architectural & Environmental Signage ───────────────────
import './templates/KineticElevatorDisplay'
import './templates/KineticHotelLobby'
import './templates/KineticNeonBuildingSign'
import './templates/KineticParkingGarage'
import './templates/KineticStadiumBoard'
import './templates/KineticStorefront'
import './templates/KineticSubwayStation'
import './templates/KineticTheaterMarquee'

// ── Round 3: Urban & Concrete ────────────────────────────────────────
import './templates/KineticConstructionFence'
import './templates/KineticManholeCover'
import './templates/KineticParkingStripe'
import './templates/KineticRollerTag'
import './templates/KineticSidewalkChalk'
import './templates/KineticSprayStencil'
import './templates/KineticUtilityMark'
import './templates/KineticWallCrack'

// ── Round 3: Neon Varieties ──────────────────────────────────────────
import './templates/KineticArgonGlow'
import './templates/KineticBlacklightUV'
import './templates/KineticBrokenNeon'
import './templates/KineticFluorescentHum'
import './templates/KineticGasTube'
import './templates/KineticMercuryVapor'
import './templates/KineticPlasmaBurn'
import './templates/KineticSodiumVapor'

// ── Round 3: Paint & Art Medium ──────────────────────────────────────
import './templates/KineticAcrylicPour'
import './templates/KineticCharcoalSmudge'
import './templates/KineticFrescoCrack'
import './templates/KineticGouacheLayer'
import './templates/KineticImpastoBrush'
import './templates/KineticOilPalette'
import './templates/KineticSprayCanDrip'
import './templates/KineticWatercolorWash'

// ── Round 3: Postal & Philatelic ─────────────────────────────────────
import './templates/KineticCertifiedMail'
import './templates/KineticEnvelopeTear'
import './templates/KineticHandCancel'
import './templates/KineticMailSlot'
import './templates/KineticPhilatelic'
import './templates/KineticPostmarkCancel'
import './templates/KineticWaxSealPress'
import './templates/KineticZipCodeSort'

// ── Round 3: Screen Technology ───────────────────────────────────────
import './templates/KineticEInkRefresh'
import './templates/KineticGreenScreen'
import './templates/KineticLaserText'
import './templates/KineticLEDMatrix'
import './templates/KineticMicrofilm'
import './templates/KineticNixieTube'
import './templates/KineticOscilloscope'
import './templates/KineticProjectionMap'

// ── Round 3: Spy & Cipher ────────────────────────────────────────────
import './templates/KineticCipherWheel'
import './templates/KineticDeadDrop'
import './templates/KineticDeclassified'
import './templates/KineticDossier'
import './templates/KineticEnigma'
import './templates/KineticInvisibleInk'
import './templates/KineticMorseCode'
import './templates/KineticSonarPing'

// ── Round 3: Vintage Computing 2 ────────────────────────────────────
import './templates/KineticAppleII'
import './templates/KineticC64Boot'
import './templates/KineticPunchCard'
import './templates/KineticRadarSweep'
import './templates/KineticRasterBar'
import './templates/KineticTeleType'
import './templates/KineticTrackerModule'
import './templates/KineticZXSpectrum'

// ── Text Physics: Elastic ─────────────────────────────────────────────
import './templates/KineticMagneticPull'
import './templates/KineticGravitySlam'
import './templates/KineticSpringOscillate'
import './templates/KineticWhipCrack'
import './templates/KineticSlingshot'
import './templates/KineticPendulumDrop'
import './templates/KineticSuctionPop'
import './templates/KineticShockwavePush'

// ── Glitch Corruption I (Hardware) ──────────────────────────────────
import './templates/KineticVHSPause'
import './templates/KineticBufferFreeze'
import './templates/KineticScreenTear'
import './templates/KineticDeadPixel'
import './templates/KineticSignalDrop'
import './templates/KineticOverheat'
import './templates/KineticInterlaceFail'
import './templates/KineticDroppedFrame'

// ── Glitch: Display Technology Failures ──────────────────────────────
import './templates/KineticLCDBleed'
import './templates/KineticOLEDBurnIn'
import './templates/KineticProjectorMisalign'
import './templates/KineticDegauss'
import './templates/KineticScanlineRoll'
import './templates/KineticGhostImage'
import './templates/KineticVerticalHold'
import './templates/KineticPhosphorDecay'

// ── Text Physics: Material ────────────────────────────────────────────
import './templates/KineticInflateText'
import './templates/KineticMeltDown'
import './templates/KineticCrumplePaper'
import './templates/KineticTaffyStretch'
import './templates/KineticShatterReform'
import './templates/KineticFreezeThaw'
import './templates/KineticSmokePuff'
import './templates/KineticRubberStretch'

// ── Text Physics: Kinetic Energy ─────────────────────────────────────
import './templates/KineticThrowCatch'
import './templates/KineticSlamDown'
import './templates/KineticRicochet'
import './templates/KineticDominoCascade'
import './templates/KineticExplosionScatter'
import './templates/KineticImplosionGather'
import './templates/KineticCentrifugeSpin'
import './templates/KineticCatapultLaunch'

// ── Geometric Reveals: Patterns ───────────────────────────────────────
import './templates/KineticCheckerReveal'
import './templates/KineticDotMatrixReveal'
import './templates/KineticLineByLine'
import './templates/KineticDiagonalSweep'
import './templates/KineticRadialBurst'
import './templates/KineticGridUnlock'
import './templates/KineticPixelBuild'
import './templates/KineticWaveSweep'

// ── Digital UI Disruption ─────────────────────────────────────────────
import './templates/KineticBlueScreen'
import './templates/KineticPopupStorm'
import './templates/KineticCaptchaResolve'
import './templates/KineticPasswordReveal'
import './templates/KineticProgressCrash'
import './templates/KineticNotificationFlood'
import './templates/KineticAutoCorrect'
import './templates/KineticClipboardPaste'

// ── Comic & Toon ────────────────────────────────────────────────────────
import './templates/KineticSpeechBubblePop'
import './templates/KineticThoughtCloud'
import './templates/KineticActionPanel'
import './templates/KineticZapBurst'
import './templates/KineticCartoonSquash'
import './templates/KineticBenDayZoom'
import './templates/KineticComicCaption'
import './templates/KineticOnomatopoeia'

// ── Comic: Panel Mechanics ───────────────────────────────────────────────
import './templates/KineticScreenTone'
import './templates/KineticSpeedLineText'
import './templates/KineticHalftoneZoom'
import './templates/KineticComicStrike'
import './templates/KineticPanelWipe'
import './templates/KineticPopArtColor'
import './templates/KineticComicInk'
import './templates/KineticKaboomScale'

// ── Art Supply Effects ────────────────────────────────────────────────
import './templates/KineticSprayPaint'
import './templates/KineticMarkerStroke'
import './templates/KineticPaintRoller'
import './templates/KineticPaletteKnife'
import './templates/KineticBallpointPen'
import './templates/KineticBrushCalligraphy'
import './templates/KineticCharcoalRub'
import './templates/KineticPastelSmear'

// ── Internet Era Nostalgia ────────────────────────────────────────────
import './templates/KineticMySpaceGlitter'
import './templates/KineticTumblrFade'
import './templates/KineticGeoCities'
import './templates/KineticWindowsXP'
import './templates/KineticDialUpConnect'
import './templates/KineticAOLInstant'
import './templates/KineticWeb1Point0'
import './templates/KineticWordArt'

// ── Round 4: Minimal Stagger & Sequence ──────────────────────────────
import './templates/KineticMinimalWave'
import './templates/KineticMinimalCascade'
import './templates/KineticMinimalDomino'
import './templates/KineticMinimalScatter'
import './templates/KineticMinimalTypeIn'
import './templates/KineticMinimalRoll'
import './templates/KineticMinimalFan'
import './templates/KineticMinimalBlink'

// ── Round 5: Minimal Motion Dynamics ─────────────────────────────────
import './templates/KineticMinimalElastic'
import './templates/KineticMinimalBreathScale'
import './templates/KineticMinimalPerspective'
import './templates/KineticMinimalSlideApart'
import './templates/KineticMinimalCountUp'
import './templates/KineticMinimalVerticalClip'
import './templates/KineticMinimalCornerPeek'
import './templates/KineticMinimalOverprint'

// ── Round 4: Film Edit Techniques ────────────────────────────────────
import './templates/KineticJumpCut'
import './templates/KineticSmashCut'
import './templates/KineticWhipPan'
import './templates/KineticFreezeFrame'
import './templates/KineticSlowMotion'
import './templates/KineticTimeLapse'
import './templates/KineticMatchCut'
import './templates/KineticCrossFade'

// ── Round 4: Stationery & Office ─────────────────────────────────────
import './templates/KineticStickyTape'
import './templates/KineticPaperClip'
import './templates/KineticRubberStamp'
import './templates/KineticIndexCard'
import './templates/KineticBinderTab'
import './templates/KineticWhiteboardWrite'
import './templates/KineticCorrectionTape'
import './templates/KineticMemoPad'

// ── Round 4: Cyberpunk & Neon Future ─────────────────────────────────
import './templates/KineticAROverlay'
import './templates/KineticAIGenText'
import './templates/KineticNeuralGlow'
import './templates/KineticLaserGrid'
import './templates/KineticNeonWireframe'
import './templates/KineticDigitalTwin'
import './templates/KineticQuantumFlicker'
import './templates/KineticDataStreamV2'

// ── Mechanical: Rotation Reveals ─────────────────────────────────────
import './templates/KineticTurntable'
import './templates/KineticRouletteWheel'
import './templates/KineticDialTurn'
import './templates/KineticCompassNeedle'
import './templates/KineticClockHand'
import './templates/KineticTurnstile'
import './templates/KineticPropellerSpin'
import './templates/KineticLazySusan'

// ── Minimal: Entrance Mechanics ───────────────────────────────────────
import './templates/KineticMinimalUnfold'
import './templates/KineticMinimalShimmer'
import './templates/KineticMinimalGrow'
import './templates/KineticMinimalDash'
import './templates/KineticMinimalInvert'
import './templates/KineticMinimalCompact'
import './templates/KineticMinimalErase'
import './templates/KineticMinimalPhase'

// ── Mechanical: Folding/Hinging ───────────────────────────────────────
import './templates/KineticGateFold'
import './templates/KineticBiFold'
import './templates/KineticTriFold'
import './templates/KineticClamshell'
import './templates/KineticFlipPhone'
import './templates/KineticLaptopLid'
import './templates/KineticTrunkOpen'
import './templates/KineticHingedFlap'

// ── Pattern: Tile Reveals ─────────────────────────────────────────────
import './templates/KineticHoneycombReveal'
import './templates/KineticBrickReveal'
import './templates/KineticHerringboneReveal'
import './templates/KineticScaleReveal'
import './templates/KineticPinwheelReveal'
import './templates/KineticDiamondTileReveal'
import './templates/KineticCirclePack'
import './templates/KineticTriangleTile'

// ── Pattern: Scan Reveals ─────────────────────────────────────────────
import './templates/KineticBarcodeSweep'
import './templates/KineticQRReveal'
import './templates/KineticThermalScan'
import './templates/KineticPhotocopyScan'
import './templates/KineticFingerprint'
import './templates/KineticXRayReveal'
import './templates/KineticMRIScan'
import './templates/KineticUPCScan'

// ── Pattern: Typography Grid ──────────────────────────────────────────
import './templates/KineticLetterGrid'
import './templates/KineticAlphabetReveal'
import './templates/KineticMonospaceGrid'
import './templates/KineticTypeSample'
import './templates/KineticKerningSnap'
import './templates/KineticFontCascade'
import './templates/KineticBaselineShift'
import './templates/KineticLeadingCompress'

// ── Glitch: Transmission Errors ───────────────────────────────────────
import './templates/KineticSatelliteMosaic'
import './templates/KineticRadioStatic'
import './templates/KineticCellDropout'
import './templates/KineticStreamBuffer'
import './templates/KineticWalkie'
import './templates/KineticFaxTransmit'
import './templates/KineticMorseFlash'
import './templates/KineticTelegraph'

// ── Glitch: File Corruption ───────────────────────────────────────────
import './templates/KineticJPEGArtifact'
import './templates/KineticPNGInterlace'
import './templates/KineticCorruptedSave'
import './templates/KineticFileRecovery'
import './templates/KineticBrokenPipe'
import './templates/KineticChecksumFail'
import './templates/KineticPartialDownload'
import './templates/KineticBitRot'

// ── Mechanical: Aperture & Iris ───────────────────────────────────────
import './templates/KineticCameraIris'
import './templates/KineticPupilDilate'
import './templates/KineticSpotlightIris'
import './templates/KineticPinholeWiden'
import './templates/KineticValveOpen'
import './templates/KineticDamRelease'
import './templates/KineticLensShutter'
import './templates/KineticPorthole'

// ── Specific Cultural Glitch ──────────────────────────────────────────
import './templates/KineticZoomFreeze'
import './templates/KineticAutoTuneGlitch'
import './templates/KineticSubtitleDeSync'
import './templates/KineticSpellcheckWave'
import './templates/KineticPredictiveText'
import './templates/KineticSiriMishear'
import './templates/KineticAutoSaveFlash'
import './templates/KineticUndoRedo'

// ── Optical & Lens Effects: Refraction ───────────────────────────────
import './templates/KineticWaterRefraction'
import './templates/KineticHeatShimmer'
import './templates/KineticGlassBlock'
import './templates/KineticCrystalFacet'

// ── Optical & Lens Effects: Aberration ───────────────────────────────
import './templates/KineticSphericalAberration'
import './templates/KineticComaDistort'
import './templates/KineticAstigmatismWarp'
import './templates/KineticFieldCurvature'

// ── Optical & Lens Effects: Interference ─────────────────────────────
import './templates/KineticThinFilmIridescence'
import './templates/KineticDiffractionGrating'
import './templates/KineticMoireGrid'
import './templates/KineticPolarizationReveal'

// ── Optical & Lens Effects: Projection ───────────────────────────────
import './templates/KineticGoboShadow'
import './templates/KineticDiscoBallScatter'
import './templates/KineticStroboscope'
import './templates/KineticLaserGridScan'

// ── Optical & Lens Effects: Reflection ───────────────────────────────
import './templates/KineticFunhouseMirror'
import './templates/KineticWaterRippleReflect'
import './templates/KineticChromeSphereMap'
import './templates/KineticAnamorphicReflect'

// ── Mechanical: Spring & Latch ────────────────────────────────────────
import './templates/KineticMousetrapSnap'
import './templates/KineticJackInBox'
import './templates/KineticSpringDoor'
import './templates/KineticSnapBracelet'
import './templates/KineticPopUpBook'
import './templates/KineticRetractPen'
import './templates/KineticToasterPop'
import './templates/KineticPinballLaunch'

// ── Text Distortion & Deformation ────────────────────────────────────
// Shatter/Fragment
import './templates/KineticVoronoiShatter'
import './templates/KineticPixelScatter'
import './templates/KineticStripSlice'
import './templates/KineticRadialExplode'
// Wave Distortion
import './templates/KineticFlagWave'
import './templates/KineticHeatMirage'
import './templates/KineticUnderwaterCaustic'
import './templates/KineticSeismicRipple'
// Compression/Expansion
import './templates/KineticHydraulicPress'
import './templates/KineticVacuumImplode'
import './templates/KineticInflationPop'
import './templates/KineticAccordionSqueeze'
// Rotation Distort
import './templates/KineticTornadoSpiral'
import './templates/KineticDNATwist'
import './templates/KineticGearTeeth'
import './templates/KineticPropellerBlur'
// Glitch Distort
import './templates/KineticScanlineDisplace'
import './templates/KineticInterlaceTear'
import './templates/KineticPixelSort'
import './templates/KineticDataBend'

// ── Glitch: Network/Protocol Errors ──────────────────────────────────
import './templates/KineticPacketDrop'
import './templates/KineticLatencySpike'
import './templates/KineticDNSResolve'
import './templates/KineticSSLHandshake'
import './templates/KineticTimeoutRetry'
import './templates/KineticCDNCache'
import './templates/KineticRateLimited'
import './templates/KineticWebSocket'

// ── Round 5: Pattern Matrix/Game Reveals ─────────────────────────────
import './templates/KineticCrosswordFill'
import './templates/KineticWordSearch'
import './templates/KineticTetrisDrop'
import './templates/KineticPixelArtBuild'
import './templates/KineticScrabbleTile'
import './templates/KineticBingoCall'
import './templates/KineticFlipDisc'
import './templates/KineticSlidePuzzle'

// ── Round 5: Mechanical Sliding/Tracking ─────────────────────────────
import './templates/KineticDrawerSlide'
import './templates/KineticRailTrack'

// ── Minimal Innovation ────────────────────────────────────────────────
// Minimal Motion: new single-property entrance mechanics
import './templates/KineticMinimalSkewIn'
import './templates/KineticMinimalTracksIn'
import './templates/KineticMinimalBaselineRise'
import './templates/KineticMinimalWeightShift'
// Minimal Transition: new transition styles between words
import './templates/KineticMinimalCrossfade'
import './templates/KineticMinimalScaleTrade'
import './templates/KineticMinimalPositionSwap'
// Minimal Texture: one subtle accent element
import './templates/KineticMinimalUnderlineDraw'
import './templates/KineticMinimalDotAccent'
import './templates/KineticMinimalBracketFrame'
import './templates/KineticMinimalEmDash'
// Minimal Rhythm: rhythmic timing patterns
import './templates/KineticMinimalCascadeChars'
import './templates/KineticMinimalAltDirection'
import './templates/KineticMinimalPingPong'
import './templates/KineticMinimalMetronome'
import './templates/KineticMinimalOpacityWave'

// ── Text Deformation ──────────────────────────────────────────────────
// Elastic/Rubber
import './templates/KineticBungeeJump'
import './templates/KineticAccordionStretch'
import './templates/KineticVibratoShake'
import './templates/KineticCoilSpring'
// Fluid/Liquid
import './templates/KineticSyrupPour'
import './templates/KineticWaterSurface'
import './templates/KineticSlimeDrool'
import './templates/KineticMercuryPool'
// Warp/Distort
import './templates/KineticVortexSuck'
import './templates/KineticShockRipple'
import './templates/KineticPinchZoom'
import './templates/KineticTwistCorkscrew'
// Morph/Transform
import './templates/KineticStrokeToFill'
import './templates/KineticWeightPump'
import './templates/KineticGhostSolid'
import './templates/KineticNegativeSpace'

// ── Cultural Moments ───────────────────────────────────────────────────
// Trending Aesthetics 2025
import './templates/KineticQuietLuxury'
import './templates/KineticMobWife'
import './templates/KineticCorporateMemphis'
import './templates/KineticCoquette'
// Music Genre Visuals
import './templates/KineticHyperpopGlitch'
import './templates/KineticDrillCondensed'
import './templates/KineticKpopLightstick'
import './templates/KineticIndieFolkHandLettered'
// Film / Show Aesthetic
import './templates/KineticWesAnderson'
import './templates/KineticElevatedHorror'
import './templates/KineticAnimeOpeningTitle'
import './templates/KineticHBOPrestige'
// Subculture Text
import './templates/KineticStanTwitter'
import './templates/KineticTechBroPitchDeck'
import './templates/KineticWholesomeCozy'
import './templates/KineticGymBroMotivation'

// ── Rhythmic & Musical ───────────────────────────────────────────────
// Impact Hits
import './templates/KineticKickDrumSlam'
import './templates/KineticSnareSnap'
import './templates/KineticHiHatStutter'
import './templates/KineticCymbalCrash'
// Wave/Pulse
import './templates/KineticSineWaveDeform'
import './templates/KineticHeartbeatPulse'
import './templates/KineticBreathingRhythm'
import './templates/KineticTidalPushPull'
// Staccato/Stutter
import './templates/KineticBeatChop'
import './templates/KineticAudioGate'
import './templates/KineticQuantizedJump'
import './templates/KineticRhythmGridSnap'
// Build/Drop
import './templates/KineticTensionBuild'
import './templates/KineticDropExplosion'
import './templates/KineticBreakdownDissolve'
import './templates/KineticAnthemSwell'

// ── Material Physics ──────────────────────────────────────────────────
// Metallic
import './templates/KineticMoltenPour'
import './templates/KineticForgedMetal'
import './templates/KineticPatinaForm'
import './templates/KineticMagneticField'
// Fabric / Fiber
import './templates/KineticFabricBillowing'
import './templates/KineticUnravelThread'
import './templates/KineticDenimFray'
import './templates/KineticSilkRipple'
// Organic / Bio
import './templates/KineticCellDivision'
import './templates/KineticBarnacleCrust'
import './templates/KineticMyceliumSpread'
import './templates/KineticVineWrap'
// State Change
import './templates/KineticFreezeForm'
import './templates/KineticEvaporate'
import './templates/KineticCondenseForm'
import './templates/KineticCrystallize'

// ── Assembly & Build-Up ───────────────────────────────────────────────
// Stroke/Draw-in
import './templates/KineticVectorStroke'
import './templates/KineticConnectDots'
import './templates/KineticGeoConstruct'
import './templates/KineticOutlineAssemble'
// Fragment Assembly
import './templates/KineticShardReform'
import './templates/KineticTornRejoin'
import './templates/KineticMagneticSnap'
import './templates/KineticPuzzleSnap'
// Growth/Organic
import './templates/KineticCrystalGrow'
import './templates/KineticIceCrystal'
import './templates/KineticCoralBuild'
import './templates/KineticFractalExpand'
// Layer Build
import './templates/KineticCMYKSplit'
import './templates/KineticScreenPrintBuild'
import './templates/KineticDepthStack'
import './templates/KineticPrintRegister'

// ── Digital Native Culture ────────────────────────────────────────────
// Creator Tools
import './templates/KineticFigmaLayer'
import './templates/KineticNotionPage'
import './templates/KineticCapCutTimeline'
import './templates/KineticSlackHuddle'
// Platform Interactions
import './templates/KineticSpotifyQueue'
import './templates/KineticDuolingoStreak'
import './templates/KineticBeRealFlash'
import './templates/KineticApplePayDing'
// AI / Tech Culture
import './templates/KineticChatGPTStream'
import './templates/KineticMidjourneyPrompt'
import './templates/KineticCopilotSuggest'
import './templates/KineticVoiceWaveform'
// Internet Moments
import './templates/KineticWordleGrid'
import './templates/KineticSentFromiPhone'
import './templates/KineticDarkPatternModal'
import './templates/KineticUberArrival'

// ── Typography Craft: Variable Font Animation ─────────────────────────
import './templates/KineticWeightBreathe'
import './templates/KineticWidthSqueeze'
import './templates/KineticOpticalSize'
import './templates/KineticSlantWave'

// ── Typography Craft: Spacing Dynamics ───────────────────────────────
import './templates/KineticTrackingPulse'
import './templates/KineticWordSpacingSnap'
import './templates/KineticJustifiedSnap'
import './templates/KineticTightLooseReveal'

// ── Typography Craft: Baseline Dance ─────────────────────────────────
import './templates/KineticBaselineWave'
import './templates/KineticSuperscriptCascade'
import './templates/KineticDropCapGrow'
import './templates/KineticHangingIndent'

// ── Typography Craft: Type Composition ───────────────────────────────
import './templates/KineticTextReflow'
import './templates/KineticColumnBreak'
import './templates/KineticPullQuoteAnimate'
import './templates/KineticTextWrapShape'

// ── Typography & Type Design: Kinetic Kerning ─────────────────────────
import './templates/KineticKernCollide'
import './templates/KineticTrackingBreath'
import './templates/KineticOpticalSnap'
import './templates/KineticMonoProportional'

// ── Typography & Type Design: Weight Animation ────────────────────────
import './templates/KineticBoldFlash'
import './templates/KineticHairlineWhisper'
import './templates/KineticWeightGradient'
import './templates/KineticBlackImpact'

// ── Typography & Type Design: Case & Style ────────────────────────────
import './templates/KineticCapsLockSlam'
import './templates/KineticItalicLean'
import './templates/KineticSmallCapsRegiment'
import './templates/KineticStrikeRedact'

// ── Typography & Type Design: Multi-Font ─────────────────────────────
import './templates/KineticSerifSansMorph'
import './templates/KineticFontRoulette'
import './templates/KineticDesignerParade'
import './templates/KineticTypewriterDisplay'

// ── Typography & Type Design: Type Anatomy ────────────────────────────
import './templates/KineticCounterFill'
import './templates/KineticDescenderDrop'
import './templates/KineticAscenderRise'
import './templates/KineticSerifGrow'

// ── Light & Shadow ────────────────────────────────────────────────────
// Shadow Play
import './templates/KineticLongShadowSweep'
import './templates/KineticShadowCast3D'
import './templates/KineticPenumbraReveal'
import './templates/KineticShadowCloneTrail'
// Backlight / Silhouette
import './templates/KineticEclipseReveal'
import './templates/KineticRimLightEdge'
import './templates/KineticContreJour'
import './templates/KineticGodRayBurst'
// Light Painting
import './templates/KineticLightPainting'
import './templates/KineticSparklerWrite'
import './templates/KineticLaserTrace'
import './templates/KineticFiberChase'
// Projection / Screen
import './templates/KineticLightboxPanel'
import './templates/KineticGoboPattern'
import './templates/KineticRearProjectScroll'
import './templates/KineticDriveInFlicker'

// ── Novel Reveal Mechanics ─────────────────────────────────────────────
// Destruction Reveals
import './templates/KineticGlassCrackReveal'
import './templates/KineticWallCrumble'
import './templates/KineticIceMeltReveal'
import './templates/KineticPaperBurnReveal'
// Overlay Peel
import './templates/KineticScratchCardReveal'
import './templates/KineticPaintChipReveal'
import './templates/KineticFogDefogReveal'
import './templates/KineticFilmPeelReveal'
// Dimensional Reveals
import './templates/KineticPortalZoom'
import './templates/KineticParallaxDepthReveal'
import './templates/KineticFoldOutEdge'
import './templates/KineticDollyThrough'
// Interference Reveals
import './templates/KineticMoireReveal'
import './templates/KineticNoiseThreshold'
import './templates/KineticHalftoneResolve'
import './templates/KineticStaticResolve'

// ── Assembly & Reveal: Scatter-to-Form ────────────────────────────────
import './templates/KineticConfettiSettle'
import './templates/KineticSnowAccumulate'
import './templates/KineticSandPour'
import './templates/KineticIronFilings'

// ── Assembly & Reveal: Line Construction ─────────────────────────────
import './templates/KineticWireframeMesh'
import './templates/KineticTopoContour'
import './templates/KineticCircuitBuild'
import './templates/KineticBlueprintDraft'

// ── Assembly & Reveal: Pixel/Grid Build ──────────────────────────────
import './templates/KineticCrosswordBuild'
import './templates/KineticTetrisStack'
import './templates/KineticLEDMatrix'
import './templates/KineticTileFlip'

// ── Assembly & Reveal: Layer Composite ───────────────────────────────
import './templates/KineticDoubleExposureBuild'
import './templates/KineticMultiplyOverlay'
import './templates/KineticScreenComposite'
import './templates/KineticDifferenceBlend'

// ── Assembly & Reveal: Chemical/Process ──────────────────────────────
import './templates/KineticDarkroomDevelop'
import './templates/KineticElectroplate'
import './templates/KineticAnodize'
import './templates/KineticAcidEtch'

// ── Minimal Motion: Transform Minimals ─────────────────────────────────────
import './templates/KineticMinimalScaleX'
import './templates/KineticMinimalRotateSnap'
import './templates/KineticMinimalDiagonal'
import './templates/KineticMinimalSkewLean'

// ── Minimal Motion: Filter Minimals ────────────────────────────────────────
import './templates/KineticMinimalContrastPunch'
import './templates/KineticMinimalSaturate'
import './templates/KineticMinimalSepiaFlash'
import './templates/KineticMinimalInvertFlip'

// ── Minimal Motion: Spacing Minimals ───────────────────────────────────────
import './templates/KineticMinimalWordSpacing'
import './templates/KineticMinimalIndent'
import './templates/KineticMinimalAlignShift'
import './templates/KineticMinimalMarginCollapse'

// ── Minimal Motion: Timing Minimals ────────────────────────────────────────
import './templates/KineticMinimalInstantCut'
import './templates/KineticMinimalSlowMo'
import './templates/KineticMinimalDoubleBounce'
import './templates/KineticMinimalStutterStep'

// ── Minimal Motion: Composition Minimals ───────────────────────────────────
import './templates/KineticMinimalCenterCorner'
import './templates/KineticMinimalSplitSwap'
import './templates/KineticMinimalVerticalStack'
import './templates/KineticMinimalSizeHierarchy'

// ── Rhythmic & Beat-Sync — Bounce Patterns ─────────────────────────────────
import './templates/KineticTripletBounce'
import './templates/KineticSwingShuffle'
import './templates/KineticFourOnFloor'
import './templates/KineticSyncopatedHop'

// ── Rhythmic & Beat-Sync — Scale Pulse ─────────────────────────────────────
import './templates/KineticSubBassThrob'
import './templates/KineticSidechainPump'
import './templates/KineticCompressorSqueeze'
import './templates/KineticLimiterClip'

// ── Rhythmic & Beat-Sync — Position Rhythm ─────────────────────────────────
import './templates/KineticPingPongDelay'
import './templates/KineticReverbTrail'
import './templates/KineticEchoCascade'
import './templates/KineticTapeLoop'

// ── Rhythmic & Beat-Sync — Visual Music ────────────────────────────────────
import './templates/KineticCrescendoGrow'
import './templates/KineticDiminuendoShrink'
import './templates/KineticFortissimoSlam'
import './templates/KineticPianissimoWhisper'

// ── Rhythmic & Beat-Sync — Genre Beats ─────────────────────────────────────
import './templates/KineticLoFiChill'
import './templates/KineticEDMBuildup'
import './templates/KineticTrapHiHat'
import './templates/KineticReggaeOffbeat'

// ── Cultural & Trending Aesthetics ─────────────────────────────────────────
// 2025 TikTok Trends
import './templates/KineticDelusionalGirlboss'
import './templates/KineticCleanGirlEra'
import './templates/KineticOldMoneyPrep'
import './templates/KineticDemureMindful'
// Brand Aesthetics
import './templates/KineticLuxuryFashionHouse'
import './templates/KineticStreetwearDrop'
import './templates/KineticTechProductLaunch'
import './templates/KineticIndieGameTrailer'
// Content Format
import './templates/KineticPOVStory'
import './templates/KineticHotTakeCallout'
import './templates/KineticUnpopularOpinion'
import './templates/KineticRatioResponse'
// Community
import './templates/KineticBookTokSerif'
import './templates/KineticFoodTokOverhead'
import './templates/KineticFitTokBold'
import './templates/KineticTravelTokCinematic'
// Era Aesthetics
import './templates/KineticNinetiesGrunge'
import './templates/KineticY2KChrome'
import './templates/KineticSeventiesDiscoGold'
import './templates/KineticArtDecoGatsby'
// Cinematic & Film — Camera Movement
import './templates/KineticCraneUpReveal'
import './templates/KineticSteadicamFloat'
import './templates/KineticDollyVertigoEffect'
import './templates/KineticFilmGateWeave'
// Cinematic & Film — Film Stock
import './templates/KineticSuper8Grain'
import './templates/KineticInfraredFalseColor'
import './templates/KineticExpiredFilmShift'
import './templates/KineticFilmHalation'
// Cinematic & Film — Edit Techniques
import './templates/KineticJCutAudioFirst'
import './templates/KineticLCutLinger'
import './templates/KineticGodCutMatch'
// Cinematic & Film — Color Grade
import './templates/KineticTealOrangeGrade'
import './templates/KineticBleachBypassDesaturate'
import './templates/KineticCrossProcessShift'
import './templates/KineticDayForNightBlue'
// Cinematic & Film — Title Design
import './templates/KineticSaulBassGeometric'
import './templates/KineticMarvelTitleSlam'
import './templates/KineticHorrorCrawl'
import './templates/KineticDocumentaryLowerThird'

// ── Digital Culture & Glitch: Render Glitch ───────────────────────────
import './templates/KineticZFightFlicker'
import './templates/KineticUVUnwrap'
import './templates/KineticPolygonTear'
import './templates/KineticShaderCompile'

// ── Digital Culture & Glitch: Compression Artifact ───────────────────
import './templates/KineticMacroblockCrush'
import './templates/KineticWebPSmear'
import './templates/KineticBitrateStutter'
import './templates/KineticSpectroGlitch'

// ── Digital Culture & Glitch: OS/App Errors ──────────────────────────
import './templates/KineticNotRespondingFrost'
import './templates/KineticForceQuitSpin'
import './templates/KineticBSODReboot'
import './templates/KineticKernelModulePanic'

// ── Digital Culture & Glitch: Network Visual ─────────────────────────
import './templates/KineticBufferSpinResolve'
import './templates/KineticThrottlePixelate'
import './templates/KineticCDNPropagation'
import './templates/KineticWebSocketReconnect'

// ── Digital Culture & Glitch: AI Artifacts ───────────────────────────
import './templates/KineticHallucinationMorph'
import './templates/KineticTokenDropout'
import './templates/KineticContextOverflow'
import './templates/KineticTemperatureMelt'

// ── R7: Print/Craft & Assembly (remaining) ─────────────────────────
import './templates/KineticBatikWax'
import './templates/KineticFeltCutout'
import './templates/KineticFlexoPlate'
import './templates/KineticMacrameKnot'
import './templates/KineticOffsetLitho'
import './templates/KineticOrigamiCrease'
import './templates/KineticPaperMarbling'
import './templates/KineticPaperWeave'
import './templates/KineticPopUpCard'
import './templates/KineticSpotUV'
import './templates/KineticThermography'
import './templates/KineticTieDyeBleed'

// ── R8: Reward-model-gated batch ──────────────────────────────────────
import './templates/KineticCarouselSpin'
import './templates/KineticLuminosityShift'
import './templates/KineticPrismFacet'
import './templates/KineticSplitFlap'
import './templates/KineticVaporCondense'
import './templates/KineticWeightDrop'
import './templates/KineticWindowBlinds'

// ── R9: Mood & Atmosphere batch ──────────────────────────────────────
import './templates/KineticDreamyEthereal'
import './templates/KineticAggressiveImpact'
import './templates/KineticElegantLuxury'
import './templates/KineticPlayfulBouncy'
import './templates/KineticEerieHorror'
