/**
 * State management for 3D animation clips (library).
 * Stores metadata for animation GLBs generated by HunyuanMotion
 * or imported from external sources.
 *
 * GLB blobs are stored in IndexedDB (character3dDB.ts).
 */
import { create } from 'zustand'
import { persist } from 'zustand/middleware'
import type { Animation3D } from '@/types/character3d'
import { get3DBlob, delete3DBlob, blobToUrl, isGlbBlob } from '@/services/character3dDB'

interface Animation3DState {
  animations: Animation3D[]
  selectedAnimationId: string | null
  /** Runtime blob URL cache (not persisted) */
  blobUrls: Record<string, string>
  /** Whether a motion generation is in progress */
  isGenerating: boolean
  generationProgress: number

  // Actions
  addAnimation: (animation: Animation3D) => void
  removeAnimation: (id: string) => void
  updateAnimation: (id: string, updates: Partial<Animation3D>) => void
  selectAnimation: (id: string | null) => void
  getSelectedAnimation: () => Animation3D | null

  // Generation state
  setGenerating: (generating: boolean) => void
  setGenerationProgress: (progress: number) => void

  // Blob URL management
  setBlobUrl: (glbBlobId: string, url: string) => void
  getBlobUrl: (glbBlobId: string) => string | null
  hydrateAllBlobUrls: () => Promise<void>

  // Reset
  reset: () => void
}

export const use3DAnimationStore = create<Animation3DState>()(
  persist(
    (set, get) => ({
      animations: [],
      selectedAnimationId: null,
      blobUrls: {},
      isGenerating: false,
      generationProgress: 0,

      addAnimation: (animation) =>
        set((state) => ({
          animations: [...state.animations, animation],
        })),

      removeAnimation: (id) => {
        const state = get()
        const anim = state.animations.find((a) => a.id === id)
        if (anim) {
          delete3DBlob(anim.glbBlobId).catch(() => {})
          const blobUrl = state.blobUrls[anim.glbBlobId]
          if (blobUrl) {
            URL.revokeObjectURL(blobUrl)
          }
        }
        set((state) => ({
          animations: state.animations.filter((a) => a.id !== id),
          selectedAnimationId:
            state.selectedAnimationId === id ? null : state.selectedAnimationId,
          blobUrls: anim
            ? Object.fromEntries(
                Object.entries(state.blobUrls).filter(([k]) => k !== anim.glbBlobId)
              )
            : state.blobUrls,
        }))
      },

      updateAnimation: (id, updates) =>
        set((state) => ({
          animations: state.animations.map((a) =>
            a.id === id ? { ...a, ...updates } : a
          ),
        })),

      selectAnimation: (id) =>
        set(() => ({
          selectedAnimationId: id,
        })),

      getSelectedAnimation: () => {
        const state = get()
        return (
          state.animations.find((a) => a.id === state.selectedAnimationId) || null
        )
      },

      setGenerating: (generating) =>
        set(() => ({
          isGenerating: generating,
          generationProgress: generating ? 0 : 0,
        })),

      setGenerationProgress: (progress) =>
        set(() => ({
          generationProgress: progress,
        })),

      setBlobUrl: (glbBlobId, url) =>
        set((state) => ({
          blobUrls: { ...state.blobUrls, [glbBlobId]: url },
        })),

      getBlobUrl: (glbBlobId) => {
        return get().blobUrls[glbBlobId] || null
      },

      hydrateAllBlobUrls: async () => {
        const { animations } = get()

        for (const anim of animations) {
          try {
            const blob = await get3DBlob(anim.glbBlobId)
            if (blob) {
              // Only create blob URLs for valid GLB files (skip FBX and other formats)
              if (!(await isGlbBlob(blob))) {
                continue
              }
              const url = blobToUrl(blob)
              set((state) => ({
                blobUrls: { ...state.blobUrls, [anim.glbBlobId]: url },
              }))
            }
          } catch {
            // Silently handle
          }
        }
      },

      reset: () =>
        set(() => ({
          animations: [],
          selectedAnimationId: null,
          blobUrls: {},
          isGenerating: false,
          generationProgress: 0,
        })),
    }),
    {
      name: 'proanimate-3d-animations',
      partialize: (state) => ({
        animations: state.animations,
        selectedAnimationId: state.selectedAnimationId,
      }),
      onRehydrateStorage: () => {
        return (state) => {
          if (!state) return
          state.hydrateAllBlobUrls()
        }
      },
    }
  )
)
