import type { AnimatableProperty, KeyframableObjectType } from '@/types/keyframes'

export const ANIMATABLE_PROPERTIES: Record<KeyframableObjectType, AnimatableProperty[]> = {
  text: [
    { key: 'freeX', label: 'X', type: 'number' },
    { key: 'freeY', label: 'Y', type: 'number' },
    { key: 'fontSize', label: 'Font Size', type: 'number', min: 8, max: 400 },
    { key: 'opacity', label: 'Opacity', type: 'number', min: 0, max: 1 },
    { key: 'rotation', label: 'Rotation', type: 'angle' },
    { key: 'zIndex', label: 'Z-Index', type: 'number', min: -100, max: 100 },
    { key: 'letterSpacing', label: 'Letter Spacing', type: 'number', min: -5, max: 20 },
    { key: 'lineHeight', label: 'Line Height', type: 'number', min: 0.5, max: 3 },
    { key: 'backgroundOpacity', label: 'BG Opacity', type: 'number', min: 0, max: 1 },
    { key: 'blur', label: 'Blur', type: 'number', min: 0, max: 50 },
  ],
  media: [
    { key: 'position.x', label: 'X', type: 'number' },
    { key: 'position.y', label: 'Y', type: 'number' },
    { key: 'scale', label: 'Scale', type: 'number', min: 0.01, max: 10 },
    { key: 'opacity', label: 'Opacity', type: 'number', min: 0, max: 1 },
    { key: 'rotation', label: 'Rotation', type: 'angle' },
    { key: 'zIndex', label: 'Z-Index', type: 'number', min: -100, max: 100 },
    { key: 'blur', label: 'Blur', type: 'number', min: 0, max: 50 },
  ],
  lottie: [
    { key: 'position.x', label: 'X', type: 'number' },
    { key: 'position.y', label: 'Y', type: 'number' },
    { key: 'scale', label: 'Scale', type: 'number', min: 0.01, max: 10 },
    { key: 'opacity', label: 'Opacity', type: 'number', min: 0, max: 1 },
    { key: 'zIndex', label: 'Z-Index', type: 'number', min: -100, max: 100 },
    { key: 'blur', label: 'Blur', type: 'number', min: 0, max: 50 },
  ],
  video: [
    { key: 'position.x', label: 'X', type: 'number' },
    { key: 'position.y', label: 'Y', type: 'number' },
    { key: 'scale', label: 'Scale', type: 'number', min: 0.01, max: 10 },
    { key: 'opacity', label: 'Opacity', type: 'number', min: 0, max: 1 },
    { key: 'rotation', label: 'Rotation', type: 'angle' },
    { key: 'zIndex', label: 'Z-Index', type: 'number', min: -100, max: 100 },
    { key: 'blur', label: 'Blur', type: 'number', min: 0, max: 50 },
  ],
  character: [
    { key: 'position.x', label: 'X', type: 'number' },
    { key: 'position.y', label: 'Y', type: 'number' },
    { key: 'rotation', label: 'Rotation', type: 'angle' },
    { key: 'scaleX', label: 'Scale X', type: 'number', min: 0.01, max: 10 },
    { key: 'scaleY', label: 'Scale Y', type: 'number', min: 0.01, max: 10 },
    { key: 'blur', label: 'Blur', type: 'number', min: 0, max: 50 },
  ],
  dialogueCharacter: [
    { key: 'position.x', label: 'X', type: 'number' },
    { key: 'position.y', label: 'Y', type: 'number' },
    { key: 'scale', label: 'Scale', type: 'number', min: 0.01, max: 10 },
    { key: 'rotation', label: 'Rotation', type: 'angle' },
    { key: 'zIndex', label: 'Z-Index', type: 'number', min: -100, max: 100 },
  ],
  shape: [
    { key: 'position.x', label: 'X', type: 'number' },
    { key: 'position.y', label: 'Y', type: 'number' },
    { key: 'width', label: 'Width', type: 'number', min: 1, max: 5000 },
    { key: 'height', label: 'Height', type: 'number', min: 1, max: 5000 },
    { key: 'opacity', label: 'Opacity', type: 'number', min: 0, max: 1 },
    { key: 'rotation', label: 'Rotation', type: 'angle' },
    { key: 'zIndex', label: 'Z-Index', type: 'number', min: -100, max: 100 },
    { key: 'strokeWidth', label: 'Stroke Width', type: 'number', min: 0, max: 50 },
    { key: 'borderRadius', label: 'Corner Radius', type: 'number', min: 0, max: 5000 },
    { key: 'innerRadius', label: 'Inner Radius', type: 'number', min: 0.1, max: 0.9 },
    { key: 'blur', label: 'Blur', type: 'number', min: 0, max: 50 },
    { key: 'gradientAngle', label: 'Gradient Angle', type: 'angle' },
    { key: 'gradientCenterX', label: 'Gradient Center X', type: 'number', min: 0, max: 1 },
    { key: 'gradientCenterY', label: 'Gradient Center Y', type: 'number', min: 0, max: 1 },
    { key: 'gradientRadius', label: 'Gradient Radius', type: 'number', min: 0, max: 2 },
    { key: 'gradientStop0Pos', label: 'Stop 1 Position', type: 'number', min: 0, max: 1 },
    { key: 'gradientStop1Pos', label: 'Stop 2 Position', type: 'number', min: 0, max: 1 },
    { key: 'gradientStop2Pos', label: 'Stop 3 Position', type: 'number', min: 0, max: 1 },
  ],
  character3d: [
    { key: 'position.x', label: 'X', type: 'number' },
    { key: 'position.y', label: 'Y', type: 'number' },
    { key: 'position.z', label: 'Z', type: 'number' },
    { key: 'rotation.x', label: 'Rot X', type: 'number' },
    { key: 'rotation.y', label: 'Rot Y', type: 'number' },
    { key: 'rotation.z', label: 'Rot Z', type: 'number' },
    { key: 'scale', label: 'Scale', type: 'number', min: 0.01, max: 10 },
    { key: 'animationSpeed', label: 'Anim Speed', type: 'number', min: 0, max: 5 },
    { key: 'blur', label: 'Blur', type: 'number', min: 0, max: 50 },
  ],
  riggedCharacter: [
    { key: 'position.x', label: 'X', type: 'number' },
    { key: 'position.y', label: 'Y', type: 'number' },
    { key: 'scale', label: 'Scale', type: 'number', min: 0.01, max: 10 },
    { key: 'rotation', label: 'Rotation', type: 'angle' },
    { key: 'zIndex', label: 'Z-Index', type: 'number', min: -100, max: 100 },
    { key: 'blur', label: 'Blur', type: 'number', min: 0, max: 50 },
  ],
  pixelArtCharacter: [
    { key: 'position.x', label: 'X', type: 'number' },
    { key: 'position.y', label: 'Y', type: 'number' },
    { key: 'scale', label: 'Scale', type: 'number', min: 0.1, max: 20 },
    { key: 'opacity', label: 'Opacity', type: 'number', min: 0, max: 1 },
    { key: 'zIndex', label: 'Z-Index', type: 'number', min: -100, max: 100 },
    { key: 'blur', label: 'Blur', type: 'number', min: 0, max: 50 },
  ],
  avatarCharacter: [
    { key: 'position.x', label: 'X', type: 'number' },
    { key: 'position.y', label: 'Y', type: 'number' },
    { key: 'scale', label: 'Scale', type: 'number', min: 0.1, max: 5 },
    { key: 'opacity', label: 'Opacity', type: 'number', min: 0, max: 1 },
    { key: 'zIndex', label: 'Z-Index', type: 'number', min: -100, max: 100 },
    { key: 'blur', label: 'Blur', type: 'number', min: 0, max: 50 },
  ],
  mask: [
    { key: 'position.x', label: 'Mask X', type: 'number' },
    { key: 'position.y', label: 'Mask Y', type: 'number' },
    { key: 'width', label: 'Mask Width', type: 'number', min: 1, max: 5000 },
    { key: 'height', label: 'Mask Height', type: 'number', min: 1, max: 5000 },
    { key: 'rotation', label: 'Mask Rotation', type: 'angle' },
    { key: 'feather', label: 'Feather', type: 'number', min: 0, max: 100 },
    { key: 'expansion', label: 'Expansion', type: 'number', min: -100, max: 100 },
  ],
  'audio-reactive': [
    { key: 'position.x', label: 'X', type: 'number' },
    { key: 'position.y', label: 'Y', type: 'number' },
    { key: 'width', label: 'Width', type: 'number', min: 1, max: 5000 },
    { key: 'height', label: 'Height', type: 'number', min: 1, max: 5000 },
    { key: 'opacity', label: 'Opacity', type: 'number', min: 0, max: 1 },
    { key: 'rotation', label: 'Rotation', type: 'angle' },
  ],
  'html-template': [
    { key: 'position.x', label: 'X', type: 'number' },
    { key: 'position.y', label: 'Y', type: 'number' },
    { key: 'scale', label: 'Scale', type: 'number', min: 0.01, max: 10 },
    { key: 'opacity', label: 'Opacity', type: 'number', min: 0, max: 1 },
    { key: 'rotation', label: 'Rotation', type: 'angle' },
  ],
}

/** Check if a property is an angle type for the given object type */
export function isAngleProperty(objectType: KeyframableObjectType, property: string): boolean {
  const props = ANIMATABLE_PROPERTIES[objectType]
  const prop = props?.find((p) => p.key === property)
  return prop?.type === 'angle'
}
