// ── AI Director: Clip Orchestration Types ──

export type CameraDirectiveType = 'pan' | 'zoom' | 'dolly' | 'orbit' | 'shake' | 'static' | 'close-up' | 'medium-shot' | 'wide-shot' | 'zoom-in' | 'dolly-in' | 'zoom-out' | 'dolly-out' | 'ken-burns' | 'pan-left' | 'pan-right' | 'pan-up' | 'pan-down'

export interface OrchestratorReferenceMedia {
  id: string
  url: string
  dataUrl?: string
  mimeType?: string
  role: 'style' | 'character' | 'scene'
  description?: string
}

export interface BeatSyncConfig {
  enabled: boolean
  intensity?: number
  syncPoints?: string[]
  subdivision?: number
  syncMediaTransitions?: boolean
  syncTextOverlays?: boolean
  syncShapeEffects?: boolean
  syncCameraZoom?: boolean
}

/** The structured plan Gemini generates from a user prompt */
export interface ClipPlan {
  canvas: {
    aspectRatio: '16:9' | '9:16' | '1:1' | '4:3' | '21:9'
    fps: number
    durationSeconds: number
    mode?: 'standard' | 'fast' | 'creative' | 'faceless'
  }

  background: {
    type: 'lottie' | 'svg-generate'
    /** For lottie: keyword(s) to match from the built-in library */
    lottieQuery?: string
    /** For svg-generate: descriptive prompt sent to Claude */
    svgPrompt?: string
  }

  characters: ClipPlanCharacter[]

  dialogue: ClipPlanDialogueLine[]

  textOverlays: ClipPlanTextOverlay[]

  shapes: ClipPlanShape[]

  htmlTemplates?: ClipPlanHTMLTemplate[]

  /** Motion graphic elements (dynamic scene templates) placed by the AI */
  motionGraphics?: ClipPlanMotionGraphic[]

  /** Individual SVG objects generated by Opus and animated via keyframes */
  svgObjects?: ClipPlanSVGObject[]

  /** Stock media assets (images/videos) searched and placed from Pixabay */
  stockMedia?: ClipPlanStockMedia[]

  /** AI-generated or library sound effects */
  soundEffects?: ClipPlanSoundEffect[]

  /** Visual engagement hooks (progress bars, countdowns, etc.) */
  retentionHooks?: ClipPlanRetentionHook[]

  /** Camera configuration for the clip */
  camera?: { presetId?: string; position?: { x: number; y: number; z: number }; rotation?: number; zoom?: number; keyframes?: Array<{ frame: number; timePercent?: number; position?: { x: number; y: number; z: number }; rotation?: number; zoom?: number; panX?: number; panY?: number; easing?: string }> }

  /** Camera directives for automated camera movements */
  cameraDirectives?: Array<{ type: string; startFrame: number; endFrame: number; startPercent?: number; endPercent?: number; intensity?: number; easing?: string; target?: string; params?: Record<string, unknown> }>

  /** Language code for the clip */
  language?: string

  /** Character gesture animations */
  gestures?: Array<{ characterId?: string; type: string; startFrame: number; endFrame: number; intensity?: number }>

  captions: {
    style: 'word-by-word' | 'sentence' | 'karaoke'
    position: 'top' | 'center' | 'bottom'
    fontSize?: number
    color?: string
    emojiMode?: 'none' | 'contextual' | 'emotion-only'
    animationSpeed?: number
    presetId?: string
  }
}

export interface ClipPlanCharacter {
  /** Display name used in dialogue lines */
  name: string
  /** Name of an existing saved character to match */
  savedCharacterName?: string
  /** If true and no saved character matches, generate via Vertex AI */
  generateNew?: boolean
  /** Description for character generation */
  referenceDescription?: string
  /** Position as percentage of canvas (0-100). x:50 = center, y:50 = middle. Converted to pixels by orchestrator. */
  position: { x: number; y: number }
  /** Scale multiplier of 200px base size (e.g. 1.5 = 300px display). */
  scale: number
  /** Preferred ElevenLabs voice name (fuzzy match) */
  voiceName?: string
  /** Whether this character is 2D sprite-based or 3D model-based. Defaults to '2d'. */
  dimension?: '2d' | '3d'
  /** Default rig animation to play when no per-line animation is specified */
  defaultAnimation?: string
  /** Character identity ID for persistent character matching */
  identityId?: string
  /** Visual style hint for character generation */
  visualStyle?: string
  /** Position/scale/rotation keyframes for character movement on canvas */
  motionKeyframes?: Array<{
    /** 0–1 fraction of total clip duration */
    timePercent: number
    /** Position as percentage of canvas (0-100) */
    position: { x: number; y: number }
    /** Scale multiplier */
    scale?: number
    /** Rotation in degrees */
    rotation?: number
    /** Easing type */
    easing?: string
  }>
}

export interface ClipPlanDialogueLine {
  characterName: string
  /** Script text, may include inline [emotion] cues */
  script: string
  /** Explicit emotion override for this line */
  emotion?: string
  /** Name of rig animation to play during this line (matched against available animations) */
  animationName?: string
}

export interface ClipPlanTextOverlay {
  preset: 'title' | 'subtitle' | 'lower-third' | 'cta' | 'quote' | 'watermark'
  content: string
  /** 0–1 fraction of total clip duration */
  startPercent: number
  endPercent: number
  fontFamily?: string
  color?: string
}

export interface ClipPlanShape {
  type: 'rectangle' | 'circle' | 'triangle' | 'star'
  position: { x: number; y: number }
  width: number
  height: number
  fill: string
  opacity?: number
  startPercent: number
  endPercent: number
}

export interface ClipPlanSVGObject {
  /** Short descriptive prompt for the SVG asset (e.g. "gold coin", "oil barrel", "fighter jet") */
  prompt: string
  /** 0–1 fraction of total clip duration */
  startPercent: number
  endPercent: number
  /** Keyframe animation: position, scale, opacity over time */
  keyframes: {
    /** 0–1 within this object's time range */
    time: number
    /** Position as % of canvas (0-100) */
    x?: number
    y?: number
    /** Scale factor (1 = 100%) */
    scale?: number
    /** Opacity 0–1 */
    opacity?: number
    /** Rotation in degrees */
    rotation?: number
  }[]
  /** Size of the SVG object in pixels */
  width?: number
  height?: number
}

export interface ClipPlanHTMLTemplate {
  /** Built-in template ID from the library (e.g. "tpl-neural-noir") */
  templateId: string
  /** Search query to fuzzy-match a template by title/tags (used if templateId doesn't match) */
  query?: string
  /** Position on canvas in pixels. Defaults to { x: 0, y: 0 } (full canvas) */
  position?: { x: number; y: number }
  /** Scale factor. Defaults to 1 */
  scale?: number
  /** 0–1 fraction of total clip duration */
  startPercent: number
  endPercent: number
  /** Config overrides for the template's editable properties */
  config?: Record<string, unknown>
  /** Optional template aspect ratio. When omitted, uses full canvas dimensions. */
  templateAspectRatio?: '16:9' | '9:16' | '1:1' | '4:3' | '21:9'
}

export interface ClipPlanMotionGraphic {
  /** Role of the motion graphic element in the visual flow */
  role: string
  /** Content fields (title, name, text, subtitle, etc.) */
  content: Record<string, string>
  /** Override accent color for the element */
  color?: string
  /** 0-1 fraction of total clip duration */
  startPercent: number
  endPercent: number
  /** Flow transition type between elements */
  transition?: string
}

export type StockMediaRole = 'background' | 'overlay' | 'cutaway' | 'accent'
export type StockMediaTransition = 'fade' | 'zoom-in' | 'zoom-out' | 'slide-left' | 'slide-right' | 'slide-up' | 'ken-burns' | 'none'

export interface ClipPlanStockMedia {
  /** Search query for Pixabay (e.g. "ocean sunset", "city traffic") */
  query: string
  /** Whether to search for an image or video */
  type: 'image' | 'video'
  /** Role determines default sizing, z-index, and behavior */
  role: StockMediaRole
  /** Position on canvas as percentage (0-100). Ignored for 'background' role (always centered). */
  position: { x: number; y: number }
  /** Scale factor relative to canvas (1 = fit to canvas, 0.5 = half, 1.2 = bleed). Auto-computed from role if omitted. */
  scale?: number
  /** 0–1 fraction of total clip duration */
  startPercent: number
  endPercent: number
  /** Entrance transition (default: 'fade') */
  enterTransition?: StockMediaTransition
  /** Exit transition (default: 'fade') */
  exitTransition?: StockMediaTransition
  /** Transition duration in seconds (default: 0.5) */
  transitionDuration?: number
  /** Optional orientation filter for Pixabay search */
  orientation?: 'horizontal' | 'vertical'
  /** Optional z-index override. Otherwise inferred from role: background=1, cutaway=4, overlay=6, accent=7 */
  zIndex?: number
  /** Creative treatment to apply (e.g. 'duotone', 'color-grade', 'vintage') */
  creativeTreatment?: string
  /** Whether to add a vignette overlay */
  addVignette?: boolean
  /** Blend mode for compositing */
  blendMode?: string
  /** Duotone preset name (e.g. 'midnight-gold') */
  duotonePreset?: string
  /** Color grade preset name (e.g. 'cinematic') */
  colorGradePreset?: string
}

/** A single scene in the visual storyboard, derived from a ClipPlan dialogue line */
export interface StoryboardScene {
  dialogueIndex: number
  characterName: string
  dialogueText: string
  emotion: string
  durationSeconds: number
  visualDescription: string
  backgroundDescription: string
  thumbnailSvg?: string
}

export interface ClipPlanSoundEffect {
  /** Descriptive prompt for the sound effect (e.g. "dramatic whoosh", "coin drop on table") */
  prompt: string
  /** Preferred source: 'generate' (ElevenLabs AI) or 'search' (Freesound library). Defaults to 'generate'. */
  source?: 'generate' | 'search'
  /** 0–1 fraction of total clip duration — when the SFX should start */
  startPercent: number
  /** Duration of the sound effect in seconds (default: auto) */
  durationSeconds?: number
  /** Volume 0–1 (default: 0.7) */
  volume?: number
}

// ── Retention Hook Types ──

export type RetentionHookType = 'progress-bar' | 'countdown' | 'chapter-marker' | 'wait-for-it' | 'step-counter'
export type RetentionHookStyle = 'minimal' | 'neon' | 'gradient' | 'branded'
export type RetentionHookPosition = 'top' | 'bottom'

export interface ClipPlanRetentionHook {
  type: RetentionHookType
  style: RetentionHookStyle
  position: RetentionHookPosition
  color?: string
  /** For countdown: starting seconds */
  countdownFrom?: number
  /** For chapter-marker: labels for each chapter */
  chapters?: string[]
  /** For wait-for-it: timestamp 0-1 when text appears */
  triggerPercent?: number
  /** For wait-for-it: custom text */
  text?: string
  /** For step-counter: total steps */
  totalSteps?: number
}

// ── Token usage & cost tracking ──

export interface TokenUsage {
  promptTokenCount: number
  candidatesTokenCount: number
  totalTokenCount: number
}

export interface TokenCost {
  usage: TokenUsage
  /** Cost in USD */
  cost: number
}

/** Individual cost entry from a single API call */
export interface CostEntry {
  source: 'gemini' | 'elevenlabs' | 'vertex-ai'
  /** Human-readable label (e.g. "Plan Generation", "Voice: Line 1") */
  label: string
  /** Cost in USD */
  cost: number
  /** In-app credits used for this operation */
  credits?: number
  /** Whether credits were refunded (operation failed) */
  refunded?: boolean
  /** For token-based APIs */
  tokenUsage?: TokenUsage
  /** For character-based APIs (ElevenLabs) */
  characters?: number
}

/** Cumulative cost tracker across all orchestration steps */
export interface OrchestrationCost {
  entries: CostEntry[]
  totalCost: number
  /** Total in-app credits used across all steps */
  totalCredits: number
}

// ── Execution tracking ──

export type StepType =
  | 'setup-canvas'
  | 'setup-background'
  | 'setup-characters'
  | 'generate-characters'
  | 'generate-voices'
  | 'setup-dialogue'
  | 'generate-music'
  | 'setup-text-overlays'
  | 'setup-shapes'
  | 'setup-html-templates'
  | 'setup-motion-graphics'
  | 'generate-svg-objects'
  | 'setup-stock-media'
  | 'setup-sound-effects'
  | 'setup-captions'
  | 'setup-camera'
  | 'setup-auto-camera'
  | 'setup-smart-broll'
  | 'setup-gestures'
  | 'setup-character-motion'
  | 'sync-to-beat'
  | 'setup-retention-hooks'
  | 'generate-thumbnail'
  | 'auto-animate-elements'
  | 'quality-gate'
  | 'finalize-timeline'

export type StepStatus = 'pending' | 'running' | 'done' | 'error' | 'skipped'

export interface OrchestratorStep {
  type: StepType
  status: StepStatus
  detail: string
  error?: string
}

export type OrchestratorPhase = 'idle' | 'planning' | 'reviewing' | 'executing' | 'comparing' | 'done' | 'error'

// ── Viral Score (Gemini plan scoring) ──

export interface ViralScoreDimensions {
  hook: number
  pacing: number
  trend: number
  emotion: number
  visual: number
  rewatch: number
}

export interface ViralScore {
  overall: number
  dimensions: ViralScoreDimensions
  suggestions: string[]
  /** Timestamp when the score was computed */
  timestamp?: number
  /** Hash of the project state at scoring time */
  projectStateHash?: string
}

// ── Pre-orchestration settings ──

export type OrchestratorAspectRatio = '16:9' | '9:16' | '1:1' | '4:3' | '21:9'

/** Lightweight character reference for pre-orchestration selection */
export interface OrchestratorCharacterRef {
  /** SavedCharacter ID */
  savedCharacterId: string
  /** Display name */
  name: string
  /** Whether this character is already on canvas (pre-selected) */
  isOnCanvas: boolean
}

export interface OrchestratorSettings {
  /** Canvas aspect ratio — defaults to current canvas aspect ratio */
  aspectRatio: OrchestratorAspectRatio
  /** Clip duration in seconds (0 = let AI decide) */
  durationSeconds: number
  /** Frames per second: 24, 30, or 60 (0 = let AI decide) */
  fps: number
  /** Whether the story needs Google search for latest info (uses grounded Gemini model) */
  useGoogleSearch: boolean
  /** Whether to generate background music */
  generateMusic: boolean
  /** Whether to generate new SVG animations (via Claude) if no befitting template is found in library */
  generateSVGAnimations: boolean
  /** Whether to generate individual SVG assets (coins, jets, etc.) via keyframe animation */
  generateSVGAssets: boolean
  /** Whether the AI can search and use Pixabay stock images/videos */
  useStockMedia: boolean
  /** Whether to generate/search sound effects for the clip */
  useSoundEffects: boolean
  /** Saved 2D character IDs selected for use in the clip (pre-populated from canvas characters) */
  selectedCharacterIds: string[]
  /** Saved 3D character IDs selected for use in the clip */
  selected3DCharacterIds: string[]
  /** Automatically include items currently on the canvas (shapes, text, characters, HTML templates) */
  includeCanvasItems: boolean
  /** Selected HTML template IDs from marketplace library */
  selectedHTMLTemplateIds: string[]
  /** Selected caption template IDs from marketplace library */
  selectedCaptionIds: string[]
  /** Selected collage IDs from marketplace library */
  selectedCollageIds: string[]
  /** Selected AI animation IDs from marketplace library */
  selectedAIAnimationIds: string[]
  /** Selected Lottie animation IDs from animation library */
  selectedAnimationIds: string[]
  /** Selected audio asset IDs from media library */
  selectedAudioIds: string[]
  /** Whether to auto-inject learned performance defaults into plan generation */
  useSmartDefaults: boolean
  /** AI learning context: recommendations from performance learning system */
  learningContext?: {
    recommendedAspectRatio?: string
    recommendedDuration?: number
    recommendedCaptionStyle?: string
    performanceInsights?: string[]
  }
  /** Brand context from Brand Director URL analysis */
  brandContext?: {
    businessName: string
    industry: string
    tone: string
    primaryColors: string[]
    tagline?: string
    /** Media store asset IDs for brand images (logo, hero, product) */
    brandImageAssetIds?: string[]
    /** Map of assetId → role (e.g. "logo", "hero", "product") */
    brandImageRoles?: Record<string, string>
  }
  /** Number of A/B variants to generate for comparison (1 = no variants, 2 or 3 = generate variants) */
  variantCount?: number
  /** Series context injected when generating an episode in a series */
  seriesContext?: {
    seriesTitle: string
    episodeNumber: number
    totalEpisodes: number
    sharedCharacters?: string[]
    previousEpisodeSummaries?: string[]
  }
  /** Reference media for style/character/scene guidance */
  referenceMedia?: OrchestratorReferenceMedia[]
  /** Orchestration mode */
  mode?: 'standard' | 'fast' | 'creative' | 'faceless'
  /** Whether to use automated camera movements */
  useAutoCamera?: boolean
  /** Whether to use smart B-roll insertion */
  useSmartBroll?: boolean
  /** Beat synchronization settings */
  beatSync?: BeatSyncConfig
  /** Whether to automatically remove backgrounds from inserted media */
  autoBgRemoval?: boolean
  /** Background removal aggressiveness */
  autoBgRemovalMode?: 'conservative' | 'aggressive'
  /** Target social media platform for optimization */
  targetPlatform?: 'tiktok' | 'youtube' | 'instagram' | 'reels'
  /** Content type for URL-extracted content */
  contentType?: 'article' | 'blog' | 'video' | 'social' | 'product' | 'recipe' | 'document' | string
  /** Extracted content from URL */
  extractedContent?: URLExtractedContent
  /** Extracted images from URL */
  extractedImages?: string[]
  /** Source URL for content-based generation */
  sourceUrl?: string
  /** Whether to auto-generate characters using AI */
  autoGenerateCharacters?: boolean
  /** Selected character identity IDs for persistent character matching */
  selectedCharacterIdentityIds?: string[]
  /** Extracted document data (PDF, PPTX) */
  extractedDocument?: unknown
}

// ── A/B Variation Config ──

export type VariationField = 'voice' | 'musicMood' | 'textStyle' | 'characterPosition' | 'template' | 'aspectRatio' | 'captionStyle' | 'pacing'

export interface VariationVariable {
  field: VariationField
  values?: string[]
}

export interface VariationConfig {
  variables: VariationVariable[]
  strategy: 'isolated' | 'random' | 'guided'
}

export interface VariantComparison {
  variantA: number
  variantB: number
  dimensionDiffs: Record<string, number>
  winner: number | null
}

// ── A/B Variant Execution ──

export interface ExecutedVariant {
  /** Index in the variants array (0 = original) */
  index: number
  /** The plan that was executed */
  plan: ClipPlan
  /** Label for UI display */
  label: string
  /** Viral score from fast analysis */
  viralScore: ViralScore | null
  /** Thumbnail data URL for comparison card */
  thumbnailDataUrl: string | null
  /** Total credits consumed */
  totalCredits: number
}

// ── URL Content Extraction ──

export interface URLExtractedContent {
  url: string
  contentType: string
  title?: string
  description?: string
  summary?: string
  keyPoints?: string[]
  tone?: string
  productPrice?: string
  productFeatures?: string[]
  extractedImages?: string[]
  suggestedPrompt?: string
  text?: string
}

// ── Article Extraction ──

export interface ArticleSection {
  heading: string
  text: string
  wordCount: number
  enabled: boolean
}

export interface ArticleExtraction {
  title: string
  author?: string
  sections: ArticleSection[]
  totalWordCount: number
  estimatedReadingTime: number
  suggestedVideoDuration: number
}

export interface ArticleVideoSettings {
  sections: ArticleSection[]
  targetDuration: number
}

// ── Batch Processing ──

export type BatchRowStatus = 'pending' | 'generating' | 'complete' | 'error'

export interface BatchRowResult {
  rowIndex: number
  status: BatchRowStatus
  videoUrl?: string
  error?: string
}
