/**
 * SCORM Export Service
 *
 * Packages a ProAnimate video export as a SCORM 1.2 or SCORM 2004 compatible
 * ZIP file that can be uploaded to LMS platforms (Moodle, Blackboard, Canvas,
 * Cornerstone, etc.).
 *
 * The SCORM package includes:
 * - imsmanifest.xml (course manifest)
 * - scormAPI.js (SCORM API adapter)
 * - index.html (launcher HTML page with video player)
 * - The exported video file
 *
 * The video player auto-reports completion to the LMS when the video finishes.
 */

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export type SCORMVersion = '1.2' | '2004'

export interface SCORMExportOptions {
  /** SCORM version (default: '1.2') */
  version?: SCORMVersion
  /** Course title */
  title: string
  /** Course description (optional) */
  description?: string
  /** Organization / author name */
  organization?: string
  /** Minimum percentage of video that must be watched for completion (0-100, default: 80) */
  completionThreshold?: number
  /** Video filename (default: 'video.mp4') */
  videoFilename?: string
}

export interface SCORMPackageResult {
  /** The ZIP blob ready for download */
  blob: Blob
  /** Suggested filename */
  filename: string
}

// ---------------------------------------------------------------------------
// SCORM manifest generation
// ---------------------------------------------------------------------------

function generateManifest12(options: SCORMExportOptions): string {
  const title = escapeXml(options.title)

  return `<?xml version="1.0" encoding="UTF-8"?>
<manifest identifier="proanimate-scorm-${Date.now()}"
  version="1.0"
  xmlns="http://www.imsproject.org/xsd/imscp_rootv1p1p2"
  xmlns:adlcp="http://www.adlnet.org/xsd/adlcp_rootv1p2"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.imsproject.org/xsd/imscp_rootv1p1p2 imscp_rootv1p1p2.xsd
    http://www.adlnet.org/xsd/adlcp_rootv1p2 adlcp_rootv1p2.xsd">

  <metadata>
    <schema>ADL SCORM</schema>
    <schemaversion>1.2</schemaversion>
  </metadata>

  <organizations default="proanimate_org">
    <organization identifier="proanimate_org">
      <title>${title}</title>
      <item identifier="item_1" identifierref="resource_1">
        <title>${title}</title>
        <adlcp:prerequisites type="aicc_script"></adlcp:prerequisites>
      </item>
    </organization>
  </organizations>

  <resources>
    <resource identifier="resource_1" type="webcontent" adlcp:scormtype="sco" href="index.html">
      <file href="index.html"/>
      <file href="scormAPI.js"/>
      <file href="${escapeXml(options.videoFilename || 'video.mp4')}"/>
    </resource>
  </resources>

</manifest>`
}

function generateManifest2004(options: SCORMExportOptions): string {
  const title = escapeXml(options.title)

  return `<?xml version="1.0" encoding="UTF-8"?>
<manifest identifier="proanimate-scorm-${Date.now()}"
  version="1.0"
  xmlns="http://www.imsglobal.org/xsd/imscp_v1p1"
  xmlns:adlcp="http://www.adlnet.org/xsd/adlcp_v1p3"
  xmlns:adlseq="http://www.adlnet.org/xsd/adlseq_v1p3"
  xmlns:adlnav="http://www.adlnet.org/xsd/adlnav_v1p3"
  xmlns:imsss="http://www.imsglobal.org/xsd/imsss"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.imsglobal.org/xsd/imscp_v1p1 imscp_v1p1.xsd
    http://www.adlnet.org/xsd/adlcp_v1p3 adlcp_v1p3.xsd
    http://www.adlnet.org/xsd/adlseq_v1p3 adlseq_v1p3.xsd
    http://www.adlnet.org/xsd/adlnav_v1p3 adlnav_v1p3.xsd
    http://www.imsglobal.org/xsd/imsss imsss_v1p0.xsd">

  <metadata>
    <schema>ADL SCORM</schema>
    <schemaversion>2004 4th Edition</schemaversion>
  </metadata>

  <organizations default="proanimate_org">
    <organization identifier="proanimate_org">
      <title>${title}</title>
      <item identifier="item_1" identifierref="resource_1">
        <title>${title}</title>
      </item>
    </organization>
  </organizations>

  <resources>
    <resource identifier="resource_1" type="webcontent" adlcp:scormType="sco" href="index.html">
      <file href="index.html"/>
      <file href="scormAPI.js"/>
      <file href="${escapeXml(options.videoFilename || 'video.mp4')}"/>
    </resource>
  </resources>

</manifest>`
}

// ---------------------------------------------------------------------------
// SCORM API adapter JS
// ---------------------------------------------------------------------------

function generateScormAPI(version: SCORMVersion, completionThreshold: number): string {
  if (version === '1.2') {
    return `/**
 * SCORM 1.2 API Adapter
 * Generated by ProAnimate SCORM Exporter
 */
(function() {
  'use strict';

  var COMPLETION_THRESHOLD = ${completionThreshold / 100};
  var api = null;
  var initialized = false;

  // Find the SCORM API object in parent/opener frames
  function findAPI(win) {
    var attempts = 0;
    while (win && !win.API && attempts < 10) {
      attempts++;
      if (win.opener && win.opener !== win) {
        win = win.opener;
      } else if (win.parent && win.parent !== win) {
        win = win.parent;
      } else {
        break;
      }
    }
    return win ? win.API || null : null;
  }

  function getAPI() {
    if (api) return api;
    api = findAPI(window);
    if (!api && window.opener) {
      api = findAPI(window.opener);
    }
    return api;
  }

  window.ScormAdapter = {
    initialize: function() {
      var lmsAPI = getAPI();
      if (lmsAPI) {
        var result = lmsAPI.LMSInitialize('');
        initialized = result === 'true' || result === true;
        if (initialized) {
          lmsAPI.LMSSetValue('cmi.core.lesson_status', 'incomplete');
          lmsAPI.LMSCommit('');
        }
      }
      return initialized;
    },

    setComplete: function() {
      var lmsAPI = getAPI();
      if (lmsAPI && initialized) {
        lmsAPI.LMSSetValue('cmi.core.lesson_status', 'completed');
        lmsAPI.LMSSetValue('cmi.core.score.raw', '100');
        lmsAPI.LMSSetValue('cmi.core.score.min', '0');
        lmsAPI.LMSSetValue('cmi.core.score.max', '100');
        lmsAPI.LMSCommit('');
      }
    },

    setProgress: function(percent) {
      // SCORM 1.2 does not have a progress measure field
      // Just check completion threshold
      if (percent >= COMPLETION_THRESHOLD) {
        this.setComplete();
      }
    },

    setSessionTime: function(seconds) {
      var lmsAPI = getAPI();
      if (lmsAPI && initialized) {
        var hours = Math.floor(seconds / 3600);
        var mins = Math.floor((seconds % 3600) / 60);
        var secs = Math.floor(seconds % 60);
        var time = String(hours).padStart(4, '0') + ':' +
                   String(mins).padStart(2, '0') + ':' +
                   String(secs).padStart(2, '0');
        lmsAPI.LMSSetValue('cmi.core.session_time', time);
        lmsAPI.LMSCommit('');
      }
    },

    terminate: function() {
      var lmsAPI = getAPI();
      if (lmsAPI && initialized) {
        lmsAPI.LMSFinish('');
        initialized = false;
      }
    },

    COMPLETION_THRESHOLD: COMPLETION_THRESHOLD
  };
})();
`
  }

  // SCORM 2004
  return `/**
 * SCORM 2004 API Adapter
 * Generated by ProAnimate SCORM Exporter
 */
(function() {
  'use strict';

  var COMPLETION_THRESHOLD = ${completionThreshold / 100};
  var api = null;
  var initialized = false;

  function findAPI(win) {
    var attempts = 0;
    while (win && !win.API_1484_11 && attempts < 10) {
      attempts++;
      if (win.opener && win.opener !== win) {
        win = win.opener;
      } else if (win.parent && win.parent !== win) {
        win = win.parent;
      } else {
        break;
      }
    }
    return win ? win.API_1484_11 || null : null;
  }

  function getAPI() {
    if (api) return api;
    api = findAPI(window);
    if (!api && window.opener) {
      api = findAPI(window.opener);
    }
    return api;
  }

  window.ScormAdapter = {
    initialize: function() {
      var lmsAPI = getAPI();
      if (lmsAPI) {
        var result = lmsAPI.Initialize('');
        initialized = result === 'true' || result === true;
        if (initialized) {
          lmsAPI.SetValue('cmi.completion_status', 'incomplete');
          lmsAPI.SetValue('cmi.success_status', 'unknown');
          lmsAPI.Commit('');
        }
      }
      return initialized;
    },

    setComplete: function() {
      var lmsAPI = getAPI();
      if (lmsAPI && initialized) {
        lmsAPI.SetValue('cmi.completion_status', 'completed');
        lmsAPI.SetValue('cmi.success_status', 'passed');
        lmsAPI.SetValue('cmi.score.scaled', '1');
        lmsAPI.SetValue('cmi.score.raw', '100');
        lmsAPI.SetValue('cmi.score.min', '0');
        lmsAPI.SetValue('cmi.score.max', '100');
        lmsAPI.Commit('');
      }
    },

    setProgress: function(percent) {
      var lmsAPI = getAPI();
      if (lmsAPI && initialized) {
        lmsAPI.SetValue('cmi.progress_measure', String(percent / 100));
        lmsAPI.Commit('');
        if (percent >= COMPLETION_THRESHOLD * 100) {
          this.setComplete();
        }
      }
    },

    setSessionTime: function(seconds) {
      var lmsAPI = getAPI();
      if (lmsAPI && initialized) {
        var hours = Math.floor(seconds / 3600);
        var mins = Math.floor((seconds % 3600) / 60);
        var secs = Math.floor(seconds % 60);
        var time = 'PT' + hours + 'H' + mins + 'M' + secs + 'S';
        lmsAPI.SetValue('cmi.session_time', time);
        lmsAPI.Commit('');
      }
    },

    terminate: function() {
      var lmsAPI = getAPI();
      if (lmsAPI && initialized) {
        lmsAPI.Terminate('');
        initialized = false;
      }
    },

    COMPLETION_THRESHOLD: COMPLETION_THRESHOLD
  };
})();
`
}

// ---------------------------------------------------------------------------
// HTML player page
// ---------------------------------------------------------------------------

function generatePlayerHTML(options: SCORMExportOptions): string {
  const title = escapeHtml(options.title)
  const videoFile = options.videoFilename || 'video.mp4'
  const threshold = options.completionThreshold || 80

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${title}</title>
  <script src="scormAPI.js"></script>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      background: #111;
      color: #fff;
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;
      min-height: 100vh;
      padding: 20px;
    }
    .container {
      max-width: 1280px;
      width: 100%;
    }
    h1 {
      font-size: 1.5rem;
      margin-bottom: 16px;
      text-align: center;
      opacity: 0.9;
    }
    .video-wrapper {
      position: relative;
      width: 100%;
      border-radius: 12px;
      overflow: hidden;
      box-shadow: 0 8px 32px rgba(0,0,0,0.5);
      background: #000;
    }
    video {
      width: 100%;
      display: block;
    }
    .progress-bar {
      height: 4px;
      background: #333;
      border-radius: 2px;
      margin-top: 16px;
      overflow: hidden;
    }
    .progress-fill {
      height: 100%;
      background: linear-gradient(90deg, #8b5cf6, #a78bfa);
      width: 0%;
      transition: width 0.3s ease;
      border-radius: 2px;
    }
    .status {
      margin-top: 12px;
      text-align: center;
      font-size: 0.875rem;
      opacity: 0.7;
    }
    .status.complete {
      color: #10b981;
      opacity: 1;
      font-weight: 600;
    }
  </style>
</head>
<body>
  <div class="container">
    <h1>${title}</h1>
    <div class="video-wrapper">
      <video id="player" controls preload="auto">
        <source src="${escapeHtml(videoFile)}" type="video/mp4">
        Your browser does not support the video element.
      </video>
    </div>
    <div class="progress-bar">
      <div class="progress-fill" id="progressFill"></div>
    </div>
    <div class="status" id="status">Watch at least ${threshold}% to complete this module</div>
  </div>

  <script>
    (function() {
      var video = document.getElementById('player');
      var progressFill = document.getElementById('progressFill');
      var statusEl = document.getElementById('status');
      var startTime = Date.now();
      var completed = false;
      var maxProgress = 0;

      // Initialize SCORM
      if (window.ScormAdapter) {
        window.ScormAdapter.initialize();
      }

      video.addEventListener('timeupdate', function() {
        if (!video.duration) return;
        var progress = (video.currentTime / video.duration) * 100;
        maxProgress = Math.max(maxProgress, progress);
        progressFill.style.width = maxProgress + '%';

        if (window.ScormAdapter) {
          window.ScormAdapter.setProgress(maxProgress);
        }

        if (!completed && maxProgress >= ${threshold}) {
          completed = true;
          statusEl.textContent = 'Module completed!';
          statusEl.className = 'status complete';
        }
      });

      video.addEventListener('ended', function() {
        maxProgress = 100;
        progressFill.style.width = '100%';
        if (window.ScormAdapter) {
          window.ScormAdapter.setComplete();
          var elapsed = Math.floor((Date.now() - startTime) / 1000);
          window.ScormAdapter.setSessionTime(elapsed);
        }
        if (!completed) {
          completed = true;
          statusEl.textContent = 'Module completed!';
          statusEl.className = 'status complete';
        }
      });

      window.addEventListener('beforeunload', function() {
        if (window.ScormAdapter) {
          var elapsed = Math.floor((Date.now() - startTime) / 1000);
          window.ScormAdapter.setSessionTime(elapsed);
          window.ScormAdapter.terminate();
        }
      });
    })();
  </script>
</body>
</html>`
}

// ---------------------------------------------------------------------------
// ZIP packaging
// ---------------------------------------------------------------------------

/**
 * Create a SCORM-compliant ZIP package containing the video and SCORM wrapper.
 *
 * @param videoBlob - The exported video as a Blob
 * @param options - SCORM packaging options
 * @returns Promise resolving to the ZIP blob and suggested filename
 */
export async function createSCORMPackage(videoBlob: Blob, options: SCORMExportOptions): Promise<SCORMPackageResult> {
  const version = options.version || '1.2'
  const completionThreshold = options.completionThreshold ?? 80
  const videoFilename = options.videoFilename || 'video.mp4'

  // Generate SCORM files
  const manifest = version === '1.2' ? generateManifest12(options) : generateManifest2004(options)

  const scormJS = generateScormAPI(version, completionThreshold)
  const playerHTML = generatePlayerHTML(options)

  // Use JSZip for packaging (dynamically imported)
  const { default: JSZip } = await import('jszip')
  const zip = new JSZip()

  // Add files to the ZIP
  zip.file('imsmanifest.xml', manifest)
  zip.file('scormAPI.js', scormJS)
  zip.file('index.html', playerHTML)
  zip.file(videoFilename, videoBlob)

  // Generate the ZIP blob
  const zipBlob = await zip.generateAsync({
    type: 'blob',
    compression: 'DEFLATE',
    compressionOptions: { level: 6 },
  })

  const safeTitle = options.title.replace(/[^a-zA-Z0-9-_]/g, '_').substring(0, 50)
  const filename = `${safeTitle}_SCORM_${version.replace('.', '')}.zip`

  return { blob: zipBlob, filename }
}

/**
 * Trigger a browser download of the SCORM package.
 */
export function downloadSCORMPackage(result: SCORMPackageResult): void {
  const url = URL.createObjectURL(result.blob)
  const a = document.createElement('a')
  a.href = url
  a.download = result.filename
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function escapeXml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;')
}

function escapeHtml(str: string): string {
  return str.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;')
}
